"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WTransport_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AccountForceOfflineNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REASON_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    WXID_FIELD_NUMBER: builtins.int
    Reason: WTransport_pb2.EnumForceOfflineReason.ValueType
    """被强制下线的原因"""
    Message: builtins.str
    """补充文字描述"""
    WxId: builtins.int
    """设备企业WX号"""
    def __init__(
        self,
        *,
        Reason: WTransport_pb2.EnumForceOfflineReason.ValueType = ...,
        Message: builtins.str = ...,
        WxId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Message", b"Message", "Reason", b"Reason", "WxId", b"WxId"]) -> None: ...

global___AccountForceOfflineNoticeMessage = AccountForceOfflineNoticeMessage
