"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AddCustomerFromSearchTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    MEMO_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    ADDBYGROUP_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Key: builtins.str
    """搜索关键字"""
    Msg: builtins.str
    """招呼语, 缺省：我是xxx公司的xxx，添加我的企业微信与我联系吧。"""
    Memo: builtins.str
    TaskId: builtins.int
    AddByGroup: builtins.bool
    @property
    def Labels(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Key: builtins.str = ...,
        Msg: builtins.str = ...,
        Memo: builtins.str = ...,
        Labels: collections.abc.Iterable[builtins.str] | None = ...,
        TaskId: builtins.int = ...,
        AddByGroup: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AddByGroup", b"AddByGroup", "Key", b"Key", "Labels", b"Labels", "Memo", b"Memo", "Msg", b"Msg", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___AddCustomerFromSearchTaskMessage = AddCustomerFromSearchTaskMessage
