"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AddCustomerByIdTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    IDS_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Msg: builtins.str
    """招呼语，缺省：你好这是我的企业微信，以后也可以在这里与我联系。"""
    TaskId: builtins.int
    @property
    def Ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """微信好友OpenId列表"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Ids: collections.abc.Iterable[builtins.str] | None = ...,
        Msg: builtins.str = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Ids", b"Ids", "Msg", b"Msg", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___AddCustomerByIdTaskMessage = AddCustomerByIdTaskMessage
