"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AddEmojiTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    IMAGE_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Image: builtins.str
    TaskId: builtins.int
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Image: builtins.str = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Image", b"Image", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___AddEmojiTaskMessage = AddEmojiTaskMessage
