"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AddCustomerByGroupTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    GROUPID_FIELD_NUMBER: builtins.int
    REMOTEID_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    MEMO_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    GroupId: builtins.int
    """搜索关键字"""
    RemoteId: builtins.int
    Msg: builtins.str
    """招呼语, 缺省：我是xxx公司的xxx，添加我的企业微信与我联系吧。"""
    Memo: builtins.str
    TaskId: builtins.int
    @property
    def Labels(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        GroupId: builtins.int = ...,
        RemoteId: builtins.int = ...,
        Msg: builtins.str = ...,
        Memo: builtins.str = ...,
        Labels: collections.abc.Iterable[builtins.str] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["GroupId", b"GroupId", "Labels", b"Labels", "Memo", b"Memo", "Msg", b"Msg", "RemoteId", b"RemoteId", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___AddCustomerByGroupTaskMessage = AddCustomerByGroupTaskMessage
