"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CommonResultMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Success: builtins.bool
    """是否成功"""
    Code: builtins.int
    """错误码 Success = true 忽略"""
    ErrMsg: builtins.str
    """错误内容描述"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Success: builtins.bool = ...,
        Code: builtins.int = ...,
        ErrMsg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Code", b"Code", "ErrMsg", b"ErrMsg", "Success", b"Success", "WxId", b"WxId"]) -> None: ...

global___CommonResultMessage = CommonResultMessage
