"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CommonTriggerTaskMessage(google.protobuf.message.Message):
    """通用Trigger任务消息"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Flag: builtins.int
    """同步会话，0：所有会话；1 已加载的会话 2 下一页会话, &512 忽略群成员 &1024 忽略消息概要
    同步客户：Flag=1 只推送单向客户id
    """
    Time: builtins.int
    """备用"""
    Offset: builtins.int
    Limit: builtins.int
    TaskId: builtins.int
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Flag: builtins.int = ...,
        Time: builtins.int = ...,
        Offset: builtins.int = ...,
        Limit: builtins.int = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Flag", b"Flag", "Limit", b"Limit", "Offset", b"Offset", "TaskId", b"TaskId", "Time", b"Time", "WxId", b"WxId"]) -> None: ...

global___CommonTriggerTaskMessage = CommonTriggerTaskMessage
