# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WConversationAddNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WConversationAddNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WConversationPushNotice_pb2 as WConversationPushNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cWConversationAddNotice.proto\x12\x10Im.Scrm.Ww.Proto\x1a\x1dWConversationPushNotice.proto\"d\n\x1c\x43onversationAddNoticeMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x36\n\x07\x43onvers\x18\x02 \x01(\x0b\x32%.Im.Scrm.Ww.Proto.ConversationMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WConversationAddNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVERSATIONADDNOTICEMESSAGE']._serialized_start=81
  _globals['_CONVERSATIONADDNOTICEMESSAGE']._serialized_end=181
# @@protoc_insertion_point(module_scope)
