"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WConversationPushNotice_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ConversationAddNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONVERS_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    @property
    def Convers(self) -> WConversationPushNotice_pb2.ConversationMessage:
        """会话"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Convers: WConversationPushNotice_pb2.ConversationMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Convers", b"Convers"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Convers", b"Convers", "WxId", b"WxId"]) -> None: ...

global___ConversationAddNoticeMessage = ConversationAddNoticeMessage
