# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WConfigSetting.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WConfigSetting.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WConfigPushNotice_pb2 as WConfigPushNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14WConfigSetting.proto\x12\x10Im.Scrm.Ww.Proto\x1a\x17WConfigPushNotice.proto\"\xc8\x01\n\x14\x43onfigSettingMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x36\n\tBoolConfs\x18\x03 \x03(\x0b\x32#.Im.Scrm.Ww.Proto.BoolConfigMessage\x12\x34\n\x08IntConfs\x18\x04 \x03(\x0b\x32\".Im.Scrm.Ww.Proto.IntConfigMessage\x12\x34\n\x08StrConfs\x18\x05 \x03(\x0b\x32\".Im.Scrm.Ww.Proto.StrConfigMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WConfigSetting_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGSETTINGMESSAGE']._serialized_start=68
  _globals['_CONFIGSETTINGMESSAGE']._serialized_end=268
# @@protoc_insertion_point(module_scope)
