"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WConversationPushNotice_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ConversationInfoNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    CONVER_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Success: builtins.bool
    """是否成功"""
    ErrMsg: builtins.str
    """错误内容描述 获取 成功时附带的结果内容"""
    TaskId: builtins.int
    @property
    def Conver(self) -> WConversationPushNotice_pb2.ConversationMessage:
        """会话"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Success: builtins.bool = ...,
        ErrMsg: builtins.str = ...,
        TaskId: builtins.int = ...,
        Conver: WConversationPushNotice_pb2.ConversationMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Conver", b"Conver"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Conver", b"Conver", "ErrMsg", b"ErrMsg", "Success", b"Success", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___ConversationInfoNoticeMessage = ConversationInfoNoticeMessage
