"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class BoolConfigMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    Key: builtins.str
    Value: builtins.bool
    Name: builtins.str
    Desc: builtins.str
    def __init__(
        self,
        *,
        Key: builtins.str = ...,
        Value: builtins.bool = ...,
        Name: builtins.str = ...,
        Desc: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Desc", b"Desc", "Key", b"Key", "Name", b"Name", "Value", b"Value"]) -> None: ...

global___BoolConfigMessage = BoolConfigMessage

@typing.final
class IntConfigMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    Key: builtins.str
    Value: builtins.int
    Name: builtins.str
    Desc: builtins.str
    def __init__(
        self,
        *,
        Key: builtins.str = ...,
        Value: builtins.int = ...,
        Name: builtins.str = ...,
        Desc: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Desc", b"Desc", "Key", b"Key", "Name", b"Name", "Value", b"Value"]) -> None: ...

global___IntConfigMessage = IntConfigMessage

@typing.final
class StrConfigMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    Key: builtins.str
    Value: builtins.str
    Name: builtins.str
    Desc: builtins.str
    def __init__(
        self,
        *,
        Key: builtins.str = ...,
        Value: builtins.str = ...,
        Name: builtins.str = ...,
        Desc: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Desc", b"Desc", "Key", b"Key", "Name", b"Name", "Value", b"Value"]) -> None: ...

global___StrConfigMessage = StrConfigMessage

@typing.final
class ConfigPushNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    BOOLCONFS_FIELD_NUMBER: builtins.int
    INTCONFS_FIELD_NUMBER: builtins.int
    STRCONFS_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    @property
    def BoolConfs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BoolConfigMessage]: ...
    @property
    def IntConfs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IntConfigMessage]: ...
    @property
    def StrConfs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StrConfigMessage]: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        BoolConfs: collections.abc.Iterable[global___BoolConfigMessage] | None = ...,
        IntConfs: collections.abc.Iterable[global___IntConfigMessage] | None = ...,
        StrConfs: collections.abc.Iterable[global___StrConfigMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["BoolConfs", b"BoolConfs", "IntConfs", b"IntConfs", "StrConfs", b"StrConfs", "WxId", b"WxId"]) -> None: ...

global___ConfigPushNoticeMessage = ConfigPushNoticeMessage
