"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WTransport_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ContactPushNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONTACTS_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Size: builtins.int
    Count: builtins.int
    Page: builtins.int
    TaskId: builtins.int
    @property
    def Contacts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ContactMessage]:
        """好友信息模型 多个"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Contacts: collections.abc.Iterable[global___ContactMessage] | None = ...,
        Size: builtins.int = ...,
        Count: builtins.int = ...,
        Page: builtins.int = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Contacts", b"Contacts", "Count", b"Count", "Page", b"Page", "Size", b"Size", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___ContactPushNoticeMessage = ContactPushNoticeMessage

@typing.final
class ContactMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REMOTEID_FIELD_NUMBER: builtins.int
    ACCTID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ALIAS_FIELD_NUMBER: builtins.int
    AVATAR_FIELD_NUMBER: builtins.int
    JOB_FIELD_NUMBER: builtins.int
    MOBILE_FIELD_NUMBER: builtins.int
    UNIONID_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    DEPARTIDS_FIELD_NUMBER: builtins.int
    ATTR_FIELD_NUMBER: builtins.int
    RemoteId: builtins.int
    """唯一id"""
    AcctId: builtins.str
    """RemoteId>>48==20 App;
    RemoteId>>48==28 微信用户;
    RemoteId>>48==33,34 外部客户；
    RemoteId>>48==39 群机器人；
    RemoteId>>48==30 内部客服；
    RemoteId>>48==32 VIP客户；
    企业内部id
    """
    Name: builtins.str
    """"""
    Alias: builtins.str
    Avatar: builtins.str
    Job: builtins.str
    """职位"""
    Mobile: builtins.str
    UnionId: builtins.str
    Gender: WTransport_pb2.EnumGender.ValueType
    Attr: builtins.int
    """属性 (attr & 64) == 64 || (attr & 33554432) == 33554432 已激活企业微信"""
    @property
    def DepartIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """所属部门id"""

    def __init__(
        self,
        *,
        RemoteId: builtins.int = ...,
        AcctId: builtins.str = ...,
        Name: builtins.str = ...,
        Alias: builtins.str = ...,
        Avatar: builtins.str = ...,
        Job: builtins.str = ...,
        Mobile: builtins.str = ...,
        UnionId: builtins.str = ...,
        Gender: WTransport_pb2.EnumGender.ValueType = ...,
        DepartIds: collections.abc.Iterable[builtins.int] | None = ...,
        Attr: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AcctId", b"AcctId", "Alias", b"Alias", "Attr", b"Attr", "Avatar", b"Avatar", "DepartIds", b"DepartIds", "Gender", b"Gender", "Job", b"Job", "Mobile", b"Mobile", "Name", b"Name", "RemoteId", b"RemoteId", "UnionId", b"UnionId"]) -> None: ...

global___ContactMessage = ContactMessage
