# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WConfigPushNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WConfigPushNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17WConfigPushNotice.proto\x12\x10Im.Scrm.Ww.Proto\"K\n\x11\x42oolConfigMessage\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\x08\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x04 \x01(\t\"J\n\x10IntConfigMessage\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\x05\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x04 \x01(\t\"J\n\x10StrConfigMessage\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\t\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x04 \x01(\t\"\xcb\x01\n\x17\x43onfigPushNoticeMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x36\n\tBoolConfs\x18\x03 \x03(\x0b\x32#.Im.Scrm.Ww.Proto.BoolConfigMessage\x12\x34\n\x08IntConfs\x18\x04 \x03(\x0b\x32\".Im.Scrm.Ww.Proto.IntConfigMessage\x12\x34\n\x08StrConfs\x18\x05 \x03(\x0b\x32\".Im.Scrm.Ww.Proto.StrConfigMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WConfigPushNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOLCONFIGMESSAGE']._serialized_start=45
  _globals['_BOOLCONFIGMESSAGE']._serialized_end=120
  _globals['_INTCONFIGMESSAGE']._serialized_start=122
  _globals['_INTCONFIGMESSAGE']._serialized_end=196
  _globals['_STRCONFIGMESSAGE']._serialized_start=198
  _globals['_STRCONFIGMESSAGE']._serialized_end=272
  _globals['_CONFIGPUSHNOTICEMESSAGE']._serialized_start=275
  _globals['_CONFIGPUSHNOTICEMESSAGE']._serialized_end=478
# @@protoc_insertion_point(module_scope)
