"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CorporationPushNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CORPS_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    @property
    def Corps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CorporationMessage]:
        """企业信息"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Corps: collections.abc.Iterable[global___CorporationMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Corps", b"Corps", "WxId", b"WxId"]) -> None: ...

global___CorporationPushNoticeMessage = CorporationPushNoticeMessage

@typing.final
class CorporationMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    Id: builtins.int
    Name: builtins.str
    def __init__(
        self,
        *,
        Id: builtins.int = ...,
        Name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Id", b"Id", "Name", b"Name"]) -> None: ...

global___CorporationMessage = CorporationMessage
