"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WCustomerPushNotice_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CustomerAddNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONTACT_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    @property
    def Contact(self) -> WCustomerPushNotice_pb2.CustomerMessage:
        """好友信息模型"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Contact: WCustomerPushNotice_pb2.CustomerMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Contact", b"Contact"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Contact", b"Contact", "WxId", b"WxId"]) -> None: ...

global___CustomerAddNoticeMessage = CustomerAddNoticeMessage
