"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CustomerGroupPushNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    GROUPS_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Success: builtins.bool
    """是否成功"""
    TaskId: builtins.int
    @property
    def Groups(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CustomerGroupMessage]:
        """客户群列表"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Success: builtins.bool = ...,
        Groups: collections.abc.Iterable[global___CustomerGroupMessage] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Groups", b"Groups", "Success", b"Success", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___CustomerGroupPushNoticeMessage = CustomerGroupPushNoticeMessage

@typing.final
class CustomerGroupMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    REMOTEID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    AVATAR_FIELD_NUMBER: builtins.int
    OWNER_FIELD_NUMBER: builtins.int
    CREATETIME_FIELD_NUMBER: builtins.int
    UPDATETIME_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    MEMBERCNT_FIELD_NUMBER: builtins.int
    Id: builtins.int
    """会话id"""
    RemoteId: builtins.int
    """会话RemoteId"""
    Name: builtins.str
    """群名"""
    Avatar: builtins.str
    Owner: builtins.int
    """群主Id"""
    CreateTime: builtins.int
    """创建时间"""
    UpdateTime: builtins.int
    """最后更新时间"""
    Flag: builtins.int
    """"""
    MemberCnt: builtins.int
    """群成员数"""
    def __init__(
        self,
        *,
        Id: builtins.int = ...,
        RemoteId: builtins.int = ...,
        Name: builtins.str = ...,
        Avatar: builtins.str = ...,
        Owner: builtins.int = ...,
        CreateTime: builtins.int = ...,
        UpdateTime: builtins.int = ...,
        Flag: builtins.int = ...,
        MemberCnt: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Avatar", b"Avatar", "CreateTime", b"CreateTime", "Flag", b"Flag", "Id", b"Id", "MemberCnt", b"MemberCnt", "Name", b"Name", "Owner", b"Owner", "RemoteId", b"RemoteId", "UpdateTime", b"UpdateTime"]) -> None: ...

global___CustomerGroupMessage = CustomerGroupMessage
