# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WCustomerGroupPushNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WCustomerGroupPushNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WTransport_pb2 as WTransport__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eWCustomerGroupPushNotice.proto\x12\x10Im.Scrm.Ww.Proto\x1a\x10WTransport.proto\"\x87\x01\n\x1e\x43ustomerGroupPushNoticeMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x0f\n\x07Success\x18\x02 \x01(\x08\x12\x36\n\x06Groups\x18\x03 \x03(\x0b\x32&.Im.Scrm.Ww.Proto.CustomerGroupMessage\x12\x0e\n\x06TaskId\x18\x04 \x01(\x03\"\xaa\x01\n\x14\x43ustomerGroupMessage\x12\n\n\x02Id\x18\x01 \x01(\x03\x12\x10\n\x08RemoteId\x18\x02 \x01(\x03\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0e\n\x06\x41vatar\x18\x04 \x01(\t\x12\r\n\x05Owner\x18\x06 \x01(\x03\x12\x12\n\nCreateTime\x18\x07 \x01(\x05\x12\x12\n\nUpdateTime\x18\x08 \x01(\x05\x12\x0c\n\x04\x46lag\x18\n \x01(\x05\x12\x11\n\tMemberCnt\x18\x0b \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WCustomerGroupPushNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMERGROUPPUSHNOTICEMESSAGE']._serialized_start=71
  _globals['_CUSTOMERGROUPPUSHNOTICEMESSAGE']._serialized_end=206
  _globals['_CUSTOMERGROUPMESSAGE']._serialized_start=209
  _globals['_CUSTOMERGROUPMESSAGE']._serialized_end=379
# @@protoc_insertion_point(module_scope)
