"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WTransport_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CustomerPushNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONTACTS_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Size: builtins.int
    Count: builtins.int
    Page: builtins.int
    TaskId: builtins.int
    @property
    def Contacts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___CustomerMessage]:
        """好友信息模型 多个"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Contacts: collections.abc.Iterable[global___CustomerMessage] | None = ...,
        Size: builtins.int = ...,
        Count: builtins.int = ...,
        Page: builtins.int = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Contacts", b"Contacts", "Count", b"Count", "Page", b"Page", "Size", b"Size", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___CustomerPushNoticeMessage = CustomerPushNoticeMessage

@typing.final
class CustomerMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REMOTEID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ALIAS_FIELD_NUMBER: builtins.int
    AVATAR_FIELD_NUMBER: builtins.int
    MOBILE_FIELD_NUMBER: builtins.int
    UNIONID_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    CORPID_FIELD_NUMBER: builtins.int
    ADDTIME_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    LABELIDS_FIELD_NUMBER: builtins.int
    SUFFIX_FIELD_NUMBER: builtins.int
    OPENID_FIELD_NUMBER: builtins.int
    SOURCEUSER_FIELD_NUMBER: builtins.int
    SOURCEROOMID_FIELD_NUMBER: builtins.int
    SOURCEFRIEND_FIELD_NUMBER: builtins.int
    APPLYCONTENT_FIELD_NUMBER: builtins.int
    REMARK_FIELD_NUMBER: builtins.int
    COMPANYREMARK_FIELD_NUMBER: builtins.int
    PHONEREMARK_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    DESCURL_FIELD_NUMBER: builtins.int
    ATTR_FIELD_NUMBER: builtins.int
    ATTR2_FIELD_NUMBER: builtins.int
    ATTR3_FIELD_NUMBER: builtins.int
    APPLYTIME_FIELD_NUMBER: builtins.int
    RemoteId: builtins.int
    """唯一id （RemoteId>>48==20 App; RemoteId>>48==28 微信用户; RemoteId>>48==33,34 外部客户； RemoteId>>48==39 群机器人； RemoteId>>48==30 内部客服； RemoteId>>48==32 VIP客户；）"""
    Name: builtins.str
    Alias: builtins.str
    Avatar: builtins.str
    Mobile: builtins.str
    UnionId: builtins.str
    """微信UnionId，可能为空"""
    Gender: WTransport_pb2.EnumGender.ValueType
    CorpId: builtins.int
    AddTime: builtins.int
    Source: builtins.int
    """添加来源"""
    Suffix: builtins.str
    """后缀"""
    OpenId: builtins.str
    SourceUser: builtins.int
    SourceRoomId: builtins.int
    SourceFriend: builtins.str
    """来自微信好友（wxid）来自通讯录（电话号码）"""
    ApplyContent: builtins.str
    Remark: builtins.str
    CompanyRemark: builtins.str
    Desc: builtins.str
    DescUrl: builtins.str
    Attr: builtins.int
    Attr2: builtins.int
    Attr3: builtins.int
    ApplyTime: builtins.int
    @property
    def LabelIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """设置的用户标签"""

    @property
    def PhoneRemark(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        RemoteId: builtins.int = ...,
        Name: builtins.str = ...,
        Alias: builtins.str = ...,
        Avatar: builtins.str = ...,
        Mobile: builtins.str = ...,
        UnionId: builtins.str = ...,
        Gender: WTransport_pb2.EnumGender.ValueType = ...,
        CorpId: builtins.int = ...,
        AddTime: builtins.int = ...,
        Source: builtins.int = ...,
        LabelIds: collections.abc.Iterable[builtins.int] | None = ...,
        Suffix: builtins.str = ...,
        OpenId: builtins.str = ...,
        SourceUser: builtins.int = ...,
        SourceRoomId: builtins.int = ...,
        SourceFriend: builtins.str = ...,
        ApplyContent: builtins.str = ...,
        Remark: builtins.str = ...,
        CompanyRemark: builtins.str = ...,
        PhoneRemark: collections.abc.Iterable[builtins.str] | None = ...,
        Desc: builtins.str = ...,
        DescUrl: builtins.str = ...,
        Attr: builtins.int = ...,
        Attr2: builtins.int = ...,
        Attr3: builtins.int = ...,
        ApplyTime: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AddTime", b"AddTime", "Alias", b"Alias", "ApplyContent", b"ApplyContent", "ApplyTime", b"ApplyTime", "Attr", b"Attr", "Attr2", b"Attr2", "Attr3", b"Attr3", "Avatar", b"Avatar", "CompanyRemark", b"CompanyRemark", "CorpId", b"CorpId", "Desc", b"Desc", "DescUrl", b"DescUrl", "Gender", b"Gender", "LabelIds", b"LabelIds", "Mobile", b"Mobile", "Name", b"Name", "OpenId", b"OpenId", "PhoneRemark", b"PhoneRemark", "Remark", b"Remark", "RemoteId", b"RemoteId", "Source", b"Source", "SourceFriend", b"SourceFriend", "SourceRoomId", b"SourceRoomId", "SourceUser", b"SourceUser", "Suffix", b"Suffix", "UnionId", b"UnionId"]) -> None: ...

global___CustomerMessage = CustomerMessage
