# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WCustomerPushNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WCustomerPushNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WTransport_pb2 as WTransport__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19WCustomerPushNotice.proto\x12\x10Im.Scrm.Ww.Proto\x1a\x10WTransport.proto\"\x99\x01\n\x19\x43ustomerPushNoticeMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x33\n\x08\x43ontacts\x18\x02 \x03(\x0b\x32!.Im.Scrm.Ww.Proto.CustomerMessage\x12\x0c\n\x04Size\x18\x03 \x01(\x05\x12\r\n\x05\x43ount\x18\x04 \x01(\x05\x12\x0c\n\x04Page\x18\x05 \x01(\x05\x12\x0e\n\x06TaskId\x18\x06 \x01(\x03\"\xf2\x03\n\x0f\x43ustomerMessage\x12\x10\n\x08RemoteId\x18\x01 \x01(\x03\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\r\n\x05\x41lias\x18\x03 \x01(\t\x12\x0e\n\x06\x41vatar\x18\x04 \x01(\t\x12\x0e\n\x06Mobile\x18\x05 \x01(\t\x12\x0f\n\x07UnionId\x18\x06 \x01(\t\x12,\n\x06Gender\x18\x07 \x01(\x0e\x32\x1c.Im.Scrm.Ww.Proto.EnumGender\x12\x0e\n\x06\x43orpId\x18\x08 \x01(\x03\x12\x0f\n\x07\x41\x64\x64Time\x18\t \x01(\x05\x12\x0e\n\x06Source\x18\n \x01(\x05\x12\x10\n\x08LabelIds\x18\x0b \x03(\x03\x12\x0e\n\x06Suffix\x18\x0c \x01(\t\x12\x0e\n\x06OpenId\x18\r \x01(\t\x12\x12\n\nSourceUser\x18\x0e \x01(\x03\x12\x14\n\x0cSourceRoomId\x18\x0f \x01(\x03\x12\x14\n\x0cSourceFriend\x18\x10 \x01(\t\x12\x14\n\x0c\x41pplyContent\x18\x11 \x01(\t\x12\x0e\n\x06Remark\x18\x12 \x01(\t\x12\x15\n\rCompanyRemark\x18\x13 \x01(\t\x12\x13\n\x0bPhoneRemark\x18\x14 \x03(\t\x12\x0c\n\x04\x44\x65sc\x18\x15 \x01(\t\x12\x0f\n\x07\x44\x65scUrl\x18\x16 \x01(\t\x12\x0c\n\x04\x41ttr\x18\x17 \x01(\x03\x12\r\n\x05\x41ttr2\x18\x18 \x01(\x03\x12\r\n\x05\x41ttr3\x18\x19 \x01(\x03\x12\x11\n\tApplyTime\x18\x1a \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WCustomerPushNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMERPUSHNOTICEMESSAGE']._serialized_start=66
  _globals['_CUSTOMERPUSHNOTICEMESSAGE']._serialized_end=219
  _globals['_CUSTOMERMESSAGE']._serialized_start=222
  _globals['_CUSTOMERMESSAGE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
