"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DaKaTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    FORCE_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Type: builtins.int
    """1 上班打卡 2 下班打卡 （未使用）"""
    Force: builtins.bool
    """强制打卡（更新打卡）"""
    Flag: builtins.int
    """保留字段，未使用 （检查时间，不允许早退等）"""
    TaskId: builtins.int
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Type: builtins.int = ...,
        Force: builtins.bool = ...,
        Flag: builtins.int = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Flag", b"Flag", "Force", b"Force", "TaskId", b"TaskId", "Type", b"Type", "WxId", b"WxId"]) -> None: ...

global___DaKaTaskMessage = DaKaTaskMessage
