# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WDepartmentPushNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WDepartmentPushNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bWDepartmentPushNotice.proto\x12\x10Im.Scrm.Ww.Proto\"q\n\x1b\x44\x65partmentPushNoticeMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x34\n\x07\x44\x65parts\x18\x02 \x03(\x0b\x32#.Im.Scrm.Ww.Proto.DepartmentMessage\x12\x0e\n\x06TaskId\x18\x03 \x01(\x03\"g\n\x11\x44\x65partmentMessage\x12\x10\n\x08RemoteId\x18\x01 \x01(\x03\x12\x10\n\x08ParentId\x18\x02 \x01(\x03\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0f\n\x07GroupId\x18\x04 \x01(\x03\x12\x0f\n\x07UserCnt\x18\x05 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WDepartmentPushNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPARTMENTPUSHNOTICEMESSAGE']._serialized_start=49
  _globals['_DEPARTMENTPUSHNOTICEMESSAGE']._serialized_end=162
  _globals['_DEPARTMENTMESSAGE']._serialized_start=164
  _globals['_DEPARTMENTMESSAGE']._serialized_end=267
# @@protoc_insertion_point(module_scope)
