"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DepartmentPushNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    DEPARTS_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    TaskId: builtins.int
    @property
    def Departs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DepartmentMessage]:
        """部门信息"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Departs: collections.abc.Iterable[global___DepartmentMessage] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Departs", b"Departs", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___DepartmentPushNoticeMessage = DepartmentPushNoticeMessage

@typing.final
class DepartmentMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REMOTEID_FIELD_NUMBER: builtins.int
    PARENTID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    GROUPID_FIELD_NUMBER: builtins.int
    USERCNT_FIELD_NUMBER: builtins.int
    RemoteId: builtins.int
    ParentId: builtins.int
    """上级部门id"""
    Name: builtins.str
    GroupId: builtins.int
    """群聊id"""
    UserCnt: builtins.int
    def __init__(
        self,
        *,
        RemoteId: builtins.int = ...,
        ParentId: builtins.int = ...,
        Name: builtins.str = ...,
        GroupId: builtins.int = ...,
        UserCnt: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["GroupId", b"GroupId", "Name", b"Name", "ParentId", b"ParentId", "RemoteId", b"RemoteId", "UserCnt", b"UserCnt"]) -> None: ...

global___DepartmentMessage = DepartmentMessage
