"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DeviceAuthReqMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _EnumAuthType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EnumAuthTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[DeviceAuthReqMessage._EnumAuthType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Default: DeviceAuthReqMessage._EnumAuthType.ValueType  # 0
        """默认方式，默认使用"""
        DeviceCode: DeviceAuthReqMessage._EnumAuthType.ValueType  # 1
        """设备码（用于手机客户端，此方式Credential应传入手机IMEI）"""
        Username: DeviceAuthReqMessage._EnumAuthType.ValueType  # 2
        """用户名密码方式（此方式Credential应传入base64(user:pwd)）"""
        InternalCode: DeviceAuthReqMessage._EnumAuthType.ValueType  # 3
        """内部服务间通讯方式（此方式Credential可为空，服务器根据ip白名单来认证）"""

    class EnumAuthType(_EnumAuthType, metaclass=_EnumAuthTypeEnumTypeWrapper):
        """认证方式枚举"""

    Default: DeviceAuthReqMessage.EnumAuthType.ValueType  # 0
    """默认方式，默认使用"""
    DeviceCode: DeviceAuthReqMessage.EnumAuthType.ValueType  # 1
    """设备码（用于手机客户端，此方式Credential应传入手机IMEI）"""
    Username: DeviceAuthReqMessage.EnumAuthType.ValueType  # 2
    """用户名密码方式（此方式Credential应传入base64(user:pwd)）"""
    InternalCode: DeviceAuthReqMessage.EnumAuthType.ValueType  # 3
    """内部服务间通讯方式（此方式Credential可为空，服务器根据ip白名单来认证）"""

    AUTHTYPE_FIELD_NUMBER: builtins.int
    CREDENTIAL_FIELD_NUMBER: builtins.int
    AuthType: global___DeviceAuthReqMessage.EnumAuthType.ValueType
    """认证方式"""
    Credential: builtins.str
    """凭证信息（不同认证方式传入不同的凭证信息）"""
    def __init__(
        self,
        *,
        AuthType: global___DeviceAuthReqMessage.EnumAuthType.ValueType = ...,
        Credential: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AuthType", b"AuthType", "Credential", b"Credential"]) -> None: ...

global___DeviceAuthReqMessage = DeviceAuthReqMessage
