"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WTransport_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DeviceAuthRspMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ExtraMessage(google.protobuf.message.Message):
        """扩展信息"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SUPPLIERID_FIELD_NUMBER: builtins.int
        UNIONID_FIELD_NUMBER: builtins.int
        ACCOUNTTYPE_FIELD_NUMBER: builtins.int
        SUPPLIERNAME_FIELD_NUMBER: builtins.int
        NICKNAME_FIELD_NUMBER: builtins.int
        TOKEN_FIELD_NUMBER: builtins.int
        SupplierId: builtins.int
        UnionId: builtins.int
        AccountType: WTransport_pb2.EnumAccountType.ValueType
        SupplierName: builtins.str
        NickName: builtins.str
        Token: builtins.str
        """访问www使用"""
        def __init__(
            self,
            *,
            SupplierId: builtins.int = ...,
            UnionId: builtins.int = ...,
            AccountType: WTransport_pb2.EnumAccountType.ValueType = ...,
            SupplierName: builtins.str = ...,
            NickName: builtins.str = ...,
            Token: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["AccountType", b"AccountType", "NickName", b"NickName", "SupplierId", b"SupplierId", "SupplierName", b"SupplierName", "Token", b"Token", "UnionId", b"UnionId"]) -> None: ...

    ACCESSTOKEN_FIELD_NUMBER: builtins.int
    EXTRA_FIELD_NUMBER: builtins.int
    AccessToken: builtins.str
    """授权成功后颁发给客户端的accesstoken"""
    @property
    def Extra(self) -> global___DeviceAuthRspMessage.ExtraMessage: ...
    def __init__(
        self,
        *,
        AccessToken: builtins.str = ...,
        Extra: global___DeviceAuthRspMessage.ExtraMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Extra", b"Extra"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["AccessToken", b"AccessToken", "Extra", b"Extra"]) -> None: ...

global___DeviceAuthRspMessage = DeviceAuthRspMessage
