# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WDownloadFileByMsgIdTask.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WDownloadFileByMsgIdTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eWDownloadFileByMsgIdTask.proto\x12\x10Im.Scrm.Ww.Proto\"\x84\x01\n\x1e\x44ownloadFileByMsgIdTaskMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\r\n\x05MsgId\x18\x02 \x01(\x03\x12\x13\n\x0bMsgRemoteId\x18\x03 \x01(\x03\x12\x10\n\x08\x46ileType\x18\x04 \x01(\x05\x12\x0e\n\x06TaskId\x18\x05 \x01(\x03\x12\x0e\n\x06ReSend\x18\x06 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WDownloadFileByMsgIdTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOWNLOADFILEBYMSGIDTASKMESSAGE']._serialized_start=53
  _globals['_DOWNLOADFILEBYMSGIDTASKMESSAGE']._serialized_end=185
# @@protoc_insertion_point(module_scope)
