"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DownloadFileByUrlTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    AESKEY_FIELD_NUMBER: builtins.int
    AUTHKEY_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    MSGTYPE_FIELD_NUMBER: builtins.int
    FILETYPE_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    RESEND_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Url: builtins.str
    """url或FileId"""
    AesKey: builtins.str
    """"""
    AuthKey: builtins.str
    """微信CDN AuthKey"""
    FileName: builtins.str
    """文件名（一般文件消息才有）"""
    MsgType: builtins.int
    """消息类型"""
    FileType: builtins.int
    """下载文件的类型 0 原始文件（原图，视频，音频，文件） 1 大图， 2 缩率图（预览图）"""
    TaskId: builtins.int
    ReSend: builtins.bool
    """重新上传文件"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Url: builtins.str = ...,
        AesKey: builtins.str = ...,
        AuthKey: builtins.str = ...,
        FileName: builtins.str = ...,
        MsgType: builtins.int = ...,
        FileType: builtins.int = ...,
        TaskId: builtins.int = ...,
        ReSend: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AesKey", b"AesKey", "AuthKey", b"AuthKey", "FileName", b"FileName", "FileType", b"FileType", "MsgType", b"MsgType", "ReSend", b"ReSend", "TaskId", b"TaskId", "Url", b"Url", "WxId", b"WxId"]) -> None: ...

global___DownloadFileByUrlTaskMessage = DownloadFileByUrlTaskMessage
