"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DownloadFileResultNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    ORGURL_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    FILETYPE_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    MSGID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Success: builtins.bool
    """是否成功"""
    ErrMsg: builtins.str
    """错误内容描述 获取 成功时附带的结果内容"""
    OrgUrl: builtins.str
    """原始URL"""
    Url: builtins.str
    """"""
    FileType: builtins.int
    """文件类型；1 大图  4 语音 5 视频 6 文件"""
    TaskId: builtins.int
    """业务的id,通用的。"""
    MsgId: builtins.int
    """消息唯一id"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Success: builtins.bool = ...,
        ErrMsg: builtins.str = ...,
        OrgUrl: builtins.str = ...,
        Url: builtins.str = ...,
        FileType: builtins.int = ...,
        TaskId: builtins.int = ...,
        MsgId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ErrMsg", b"ErrMsg", "FileType", b"FileType", "MsgId", b"MsgId", "OrgUrl", b"OrgUrl", "Success", b"Success", "TaskId", b"TaskId", "Url", b"Url", "WxId", b"WxId"]) -> None: ...

global___DownloadFileResultNoticeMessage = DownloadFileResultNoticeMessage
