"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WTransport_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ErrorMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERRORCODE_FIELD_NUMBER: builtins.int
    ERRORMSG_FIELD_NUMBER: builtins.int
    ErrorCode: WTransport_pb2.EnumErrorCode.ValueType
    """错误码（只在响应类消息时需要赋值)"""
    ErrorMsg: builtins.str
    """错误信息（只在响应类消息时需要赋值）"""
    def __init__(
        self,
        *,
        ErrorCode: WTransport_pb2.EnumErrorCode.ValueType = ...,
        ErrorMsg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ErrorCode", b"ErrorCode", "ErrorMsg", b"ErrorMsg"]) -> None: ...

global___ErrorMessage = ErrorMessage
