"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ForwardMultiTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    MSGIDS_FIELD_NUMBER: builtins.int
    CONVIDS_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    LOCALIDS_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    TaskId: builtins.int
    """任务id 在TaskResult中回传"""
    @property
    def MsgIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """消息remoteid"""

    @property
    def ConvIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """会话remoteid"""

    @property
    def LocalIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """会话Id"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        MsgIds: collections.abc.Iterable[builtins.int] | None = ...,
        ConvIds: collections.abc.Iterable[builtins.int] | None = ...,
        TaskId: builtins.int = ...,
        LocalIds: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ConvIds", b"ConvIds", "LocalIds", b"LocalIds", "MsgIds", b"MsgIds", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___ForwardMultiTaskMessage = ForwardMultiTaskMessage
