"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WPullMySnsListTaskResultNotice_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetSnsDataTaskResultNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    SNSINFO_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Success: builtins.bool
    """是否成功"""
    ErrMsg: builtins.str
    """错误内容描述 获取 成功时附带的结果内容"""
    TaskId: builtins.int
    """任务id 在TaskResult中回传"""
    @property
    def SnsInfo(self) -> WPullMySnsListTaskResultNotice_pb2.SnsInfoMessage: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Success: builtins.bool = ...,
        ErrMsg: builtins.str = ...,
        SnsInfo: WPullMySnsListTaskResultNotice_pb2.SnsInfoMessage | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["SnsInfo", b"SnsInfo"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ErrMsg", b"ErrMsg", "SnsInfo", b"SnsInfo", "Success", b"Success", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___GetSnsDataTaskResultNoticeMessage = GetSnsDataTaskResultNoticeMessage
