"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WTransport_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetWeChatsReqMessage(google.protobuf.message.Message):
    """定义消息类型 GetWeChatsReq"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNTTYPE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    AccountType: WTransport_pb2.EnumAccountType.ValueType
    """对应AccountType字段"""
    id: builtins.str
    """对应id字段"""
    def __init__(
        self,
        *,
        AccountType: WTransport_pb2.EnumAccountType.ValueType = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AccountType", b"AccountType", "id", b"id"]) -> None: ...

global___GetWeChatsReqMessage = GetWeChatsReqMessage
