"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ExtUserIdMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REMOTEID_FIELD_NUMBER: builtins.int
    EXTUID_FIELD_NUMBER: builtins.int
    RemoteId: builtins.int
    ExtUid: builtins.str
    def __init__(
        self,
        *,
        RemoteId: builtins.int = ...,
        ExtUid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ExtUid", b"ExtUid", "RemoteId", b"RemoteId"]) -> None: ...

global___ExtUserIdMessage = ExtUserIdMessage

@typing.final
class GetExtUserIdTaskResultMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    EXTUSERIDS_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Success: builtins.bool
    """是否成功"""
    ErrMsg: builtins.str
    """错误内容描述 获取 成功时附带的结果内容"""
    TaskId: builtins.int
    """任务id 在TaskResult中回传"""
    @property
    def ExtUserIds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ExtUserIdMessage]: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Success: builtins.bool = ...,
        ErrMsg: builtins.str = ...,
        ExtUserIds: collections.abc.Iterable[global___ExtUserIdMessage] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ErrMsg", b"ErrMsg", "ExtUserIds", b"ExtUserIds", "Success", b"Success", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___GetExtUserIdTaskResultMessage = GetExtUserIdTaskResultMessage
