"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetWeChatsReqMessage(google.protobuf.message.Message):
    """定义消息类型 GetWeChatsReq"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTENT_FIELD_NUMBER: builtins.int
    @property
    def content(self) -> global___Content:
        """包含一个Content消息"""

    def __init__(
        self,
        *,
        content: global___Content | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["content", b"content"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["content", b"content"]) -> None: ...

global___GetWeChatsReqMessage = GetWeChatsReqMessage

@typing.final
class Content(google.protobuf.message.Message):
    """定义Content消息"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNTTYPE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    AccountType: builtins.str
    """对应AccountType字段"""
    id: builtins.str
    """对应id字段"""
    def __init__(
        self,
        *,
        AccountType: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AccountType", b"AccountType", "id", b"id"]) -> None: ...

global___Content = Content
