"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetExtUserIdTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CORPID_FIELD_NUMBER: builtins.int
    REMOTEID_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    CorpId: builtins.str
    """公司id"""
    TaskId: builtins.int
    @property
    def RemoteId(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """客户id"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        CorpId: builtins.str = ...,
        RemoteId: collections.abc.Iterable[builtins.int] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["CorpId", b"CorpId", "RemoteId", b"RemoteId", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___GetExtUserIdTaskMessage = GetExtUserIdTaskMessage
