"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetWeChatsRespMessage(google.protobuf.message.Message):
    """定义消息类型 GetWeChatsResp"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MSGTYPE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    msgType: builtins.str
    """对应msgType字段"""
    @property
    def message(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Message]:
        """对应message字段, 是个Json数组，使用repeated类型"""

    def __init__(
        self,
        *,
        msgType: builtins.str = ...,
        message: collections.abc.Iterable[global___Message] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["message", b"message", "msgType", b"msgType"]) -> None: ...

global___GetWeChatsRespMessage = GetWeChatsRespMessage

@typing.final
class Message(google.protobuf.message.Message):
    """定义单个微信用户的消息格式"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCOUNTID_FIELD_NUMBER: builtins.int
    ALIAS_FIELD_NUMBER: builtins.int
    AVATAR_FIELD_NUMBER: builtins.int
    BRAND_FIELD_NUMBER: builtins.int
    CID_FIELD_NUMBER: builtins.int
    CORPID_FIELD_NUMBER: builtins.int
    DEVICEID_FIELD_NUMBER: builtins.int
    DEVNICKNAME_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    ISONLINE_FIELD_NUMBER: builtins.int
    JOB_FIELD_NUMBER: builtins.int
    LOGIN_TIME_FIELD_NUMBER: builtins.int
    MODIFY_TIME_FIELD_NUMBER: builtins.int
    MODULE_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    PHONE_FIELD_NUMBER: builtins.int
    WXID_FIELD_NUMBER: builtins.int
    accountid: builtins.int
    """对应accountid字段"""
    alias: builtins.str
    """对应alias字段"""
    avatar: builtins.str
    """对应avatar字段"""
    brand: builtins.str
    """对应brand字段"""
    cid: builtins.int
    """对应cid字段"""
    corpid: builtins.str
    """对应corpid字段"""
    deviceid: builtins.str
    """对应deviceid字段"""
    devnickname: builtins.str
    """对应devnickname字段"""
    gender: builtins.int
    """对应gender字段"""
    id: builtins.int
    """对应id字段"""
    isonline: builtins.int
    """对应isonline字段"""
    job: builtins.str
    """对应job字段"""
    login_time: builtins.int
    """对应login_time字段（作为时间戳）"""
    modify_time: builtins.int
    """对应modify_time字段（作为时间戳）"""
    module: builtins.str
    """对应module字段"""
    name: builtins.str
    """对应name字段"""
    phone: builtins.str
    """对应phone字段"""
    wxid: builtins.str
    """对应wxid字段"""
    def __init__(
        self,
        *,
        accountid: builtins.int = ...,
        alias: builtins.str = ...,
        avatar: builtins.str = ...,
        brand: builtins.str = ...,
        cid: builtins.int = ...,
        corpid: builtins.str = ...,
        deviceid: builtins.str = ...,
        devnickname: builtins.str = ...,
        gender: builtins.int = ...,
        id: builtins.int = ...,
        isonline: builtins.int = ...,
        job: builtins.str = ...,
        login_time: builtins.int = ...,
        modify_time: builtins.int = ...,
        module: builtins.str = ...,
        name: builtins.str = ...,
        phone: builtins.str = ...,
        wxid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["accountid", b"accountid", "alias", b"alias", "avatar", b"avatar", "brand", b"brand", "cid", b"cid", "corpid", b"corpid", "deviceid", b"deviceid", "devnickname", b"devnickname", "gender", b"gender", "id", b"id", "isonline", b"isonline", "job", b"job", "login_time", b"login_time", "modify_time", b"modify_time", "module", b"module", "name", b"name", "phone", b"phone", "wxid", b"wxid"]) -> None: ...

global___Message = Message
