# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WGetWeChatsResp.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WGetWeChatsResp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15WGetWeChatsResp.proto\x12\x10Im.Scrm.Ww.Proto\"T\n\x15GetWeChatsRespMessage\x12\x0f\n\x07msgType\x18\x01 \x01(\t\x12*\n\x07message\x18\x02 \x03(\x0b\x32\x19.Im.Scrm.Ww.Proto.Message\"\xad\x02\n\x07Message\x12\x11\n\taccountid\x18\x01 \x01(\x05\x12\r\n\x05\x61lias\x18\x02 \x01(\t\x12\x0e\n\x06\x61vatar\x18\x03 \x01(\t\x12\r\n\x05\x62rand\x18\x04 \x01(\t\x12\x0b\n\x03\x63id\x18\x05 \x01(\x05\x12\x0e\n\x06\x63orpid\x18\x06 \x01(\t\x12\x10\n\x08\x64\x65viceid\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65vnickname\x18\x08 \x01(\t\x12\x0e\n\x06gender\x18\t \x01(\x05\x12\n\n\x02id\x18\n \x01(\x05\x12\x10\n\x08isonline\x18\x0b \x01(\x05\x12\x0b\n\x03job\x18\x0c \x01(\t\x12\x12\n\nlogin_time\x18\r \x01(\x03\x12\x13\n\x0bmodify_time\x18\x0e \x01(\x03\x12\x0e\n\x06module\x18\x0f \x01(\t\x12\x0c\n\x04name\x18\x10 \x01(\t\x12\r\n\x05phone\x18\x11 \x01(\t\x12\x0c\n\x04wxid\x18\x12 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WGetWeChatsResp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETWECHATSRESPMESSAGE']._serialized_start=43
  _globals['_GETWECHATSRESPMESSAGE']._serialized_end=127
  _globals['_MESSAGE']._serialized_start=130
  _globals['_MESSAGE']._serialized_end=431
# @@protoc_insertion_point(module_scope)
