# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WGetWeChatsReq.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WGetWeChatsReq.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WTransport_pb2 as WTransport__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14WGetWeChatsReq.proto\x12\x10Im.Scrm.Ww.Proto\x1a\x10WTransport.proto\"Z\n\x14GetWeChatsReqMessage\x12\x36\n\x0b\x41\x63\x63ountType\x18\x01 \x01(\x0e\x32!.Im.Scrm.Ww.Proto.EnumAccountType\x12\n\n\x02id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WGetWeChatsReq_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETWECHATSREQMESSAGE']._serialized_start=60
  _globals['_GETWECHATSREQMESSAGE']._serialized_end=150
# @@protoc_insertion_point(module_scope)
