"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WConversationPushNotice_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GroupMemberDelNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONVID_FIELD_NUMBER: builtins.int
    CONVNAME_FIELD_NUMBER: builtins.int
    MEMBERS_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    ConvId: builtins.int
    """群聊remoteId"""
    ConvName: builtins.str
    @property
    def Members(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[WConversationPushNotice_pb2.ConvMemberMessage]:
        """群成员"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        ConvId: builtins.int = ...,
        ConvName: builtins.str = ...,
        Members: collections.abc.Iterable[WConversationPushNotice_pb2.ConvMemberMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ConvId", b"ConvId", "ConvName", b"ConvName", "Members", b"Members", "WxId", b"WxId"]) -> None: ...

global___GroupMemberDelNoticeMessage = GroupMemberDelNoticeMessage
