"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class JoinGroupInviteTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONVID_FIELD_NUMBER: builtins.int
    SENDER_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    ConvId: builtins.int
    """会话 RemoteId"""
    Sender: builtins.int
    """消息发送者RemoteId"""
    Url: builtins.str
    """邀请链接"""
    TaskId: builtins.int
    """发送给手机端的时候需要赋值，"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        ConvId: builtins.int = ...,
        Sender: builtins.int = ...,
        Url: builtins.str = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ConvId", b"ConvId", "Sender", b"Sender", "TaskId", b"TaskId", "Url", b"Url", "WxId", b"WxId"]) -> None: ...

global___JoinGroupInviteTaskMessage = JoinGroupInviteTaskMessage
