"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MsgRevokeNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONVID_FIELD_NUMBER: builtins.int
    MSGID_FIELD_NUMBER: builtins.int
    MSGREMOTEID_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    LOCALID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    ConvId: builtins.int
    """会话RemoteId"""
    MsgId: builtins.int
    """服务端的主键id"""
    MsgRemoteId: builtins.int
    """消息唯一id"""
    Flag: builtins.int
    LocalId: builtins.int
    """会话LocalId"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        ConvId: builtins.int = ...,
        MsgId: builtins.int = ...,
        MsgRemoteId: builtins.int = ...,
        Flag: builtins.int = ...,
        LocalId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ConvId", b"ConvId", "Flag", b"Flag", "LocalId", b"LocalId", "MsgId", b"MsgId", "MsgRemoteId", b"MsgRemoteId", "WxId", b"WxId"]) -> None: ...

global___MsgRevokeNoticeMessage = MsgRevokeNoticeMessage
