"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WCustomerPushNotice_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class NewCustomerPushNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONTACTS_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    TaskId: builtins.int
    @property
    def Contacts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[WCustomerPushNotice_pb2.CustomerMessage]:
        """好友信息模型 多个"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Contacts: collections.abc.Iterable[WCustomerPushNotice_pb2.CustomerMessage] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Contacts", b"Contacts", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___NewCustomerPushNoticeMessage = NewCustomerPushNoticeMessage
