"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PhoneStateTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    IMEI_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Imei: builtins.str
    """WechatId和imei用于服务端选择通道，对客户端无用"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Imei: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Imei", b"Imei", "WxId", b"WxId"]) -> None: ...

global___PhoneStateTaskMessage = PhoneStateTaskMessage
