"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PhoneStateTaskResultNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    IMEI_FIELD_NUMBER: builtins.int
    BATTERYLEVEL_FIELD_NUMBER: builtins.int
    CHARGINGSTATE_FIELD_NUMBER: builtins.int
    NETTYPE_FIELD_NUMBER: builtins.int
    SDCARDFREE_FIELD_NUMBER: builtins.int
    SDCARDTOTAL_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Imei: builtins.str
    """"""
    BatteryLevel: builtins.int
    """剩余电量百分比"""
    ChargingState: builtins.int
    """0 未知 1 充电 2 满电 3 未充电"""
    NetType: builtins.str
    """联网方式 4G WIFI"""
    SdcardFree: builtins.int
    """外部存储（sdcard）剩余空间字节数"""
    SdcardTotal: builtins.int
    """外部存储（sdcard）总空间字节数"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Imei: builtins.str = ...,
        BatteryLevel: builtins.int = ...,
        ChargingState: builtins.int = ...,
        NetType: builtins.str = ...,
        SdcardFree: builtins.int = ...,
        SdcardTotal: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["BatteryLevel", b"BatteryLevel", "ChargingState", b"ChargingState", "Imei", b"Imei", "NetType", b"NetType", "SdcardFree", b"SdcardFree", "SdcardTotal", b"SdcardTotal", "WxId", b"WxId"]) -> None: ...

global___PhoneStateTaskResultNoticeMessage = PhoneStateTaskResultNoticeMessage
