# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WPhoneActionTask.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WPhoneActionTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16WPhoneActionTask.proto\x12\x10Im.Scrm.Ww.Proto\"\x9b\x01\n\x16PhoneActionTaskMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x0c\n\x04Imei\x18\x02 \x01(\t\x12\x31\n\x06\x41\x63tion\x18\x03 \x01(\x0e\x32!.Im.Scrm.Ww.Proto.EnumPhoneAction\x12\x10\n\x08StrParam\x18\x04 \x01(\t\x12\x10\n\x08IntParam\x18\x05 \x01(\x05\x12\x0e\n\x06TaskId\x18\x06 \x01(\x03*\x82\x01\n\x0f\x45numPhoneAction\x12\x08\n\x04None\x10\x00\x12\n\n\x06Reboot\x10\x01\x12\r\n\tUploadLog\x10\x02\x12\x0e\n\nUploadFile\x10\x03\x12\x11\n\rCleanAppCache\x10\x04\x12\x10\n\x0c\x43leanWxCache\x10\x05\x12\x15\n\x11\x43leanFileUrlCache\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WPhoneActionTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENUMPHONEACTION']._serialized_start=203
  _globals['_ENUMPHONEACTION']._serialized_end=333
  _globals['_PHONEACTIONTASKMESSAGE']._serialized_start=45
  _globals['_PHONEACTIONTASKMESSAGE']._serialized_end=200
# @@protoc_insertion_point(module_scope)
