# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WPostSnsTask.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WPostSnsTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12WPostSnsTask.proto\x12\x10Im.Scrm.Ww.Proto\"\xe1\x01\n\x12PostSnsTaskMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x0f\n\x07\x43ontent\x18\x02 \x01(\t\x12-\n\x05Media\x18\x03 \x01(\x0b\x32\x1e.Im.Scrm.Ww.Proto.MediaMessage\x12\x0f\n\x07\x43omment\x18\x04 \x01(\t\x12\x31\n\x07Visible\x18\x05 \x01(\x0b\x32 .Im.Scrm.Ww.Proto.VisibleMessage\x12\x0e\n\x06TaskId\x18\x06 \x01(\x03\x12)\n\x03Poi\x18\x07 \x01(\x0b\x32\x1c.Im.Scrm.Ww.Proto.PoiMessage\"\x90\x01\n\x0cMediaMessage\x12;\n\x04Type\x18\x01 \x01(\x0e\x32-.Im.Scrm.Ww.Proto.MediaMessage.EnumAttachType\x12\x0f\n\x07\x43ontent\x18\x02 \x03(\t\"2\n\x0e\x45numAttachType\x12\x0b\n\x07Picture\x10\x00\x12\t\n\x05Video\x10\x01\x12\x08\n\x04Link\x10\x02\"3\n\x0eVisibleMessage\x12\x0f\n\x07userIds\x18\x01 \x03(\x03\x12\x10\n\x08labelIds\x18\x02 \x03(\x03\"V\n\nPoiMessage\x12\x0c\n\x04\x43ity\x18\x01 \x01(\t\x12\x0f\n\x07\x41\x64\x64ress\x18\x02 \x01(\t\x12\x0f\n\x07PoiName\x18\x03 \x01(\t\x12\x0b\n\x03Lon\x18\x04 \x01(\x01\x12\x0b\n\x03Lat\x18\x05 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WPostSnsTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTSNSTASKMESSAGE']._serialized_start=41
  _globals['_POSTSNSTASKMESSAGE']._serialized_end=266
  _globals['_MEDIAMESSAGE']._serialized_start=269
  _globals['_MEDIAMESSAGE']._serialized_end=413
  _globals['_MEDIAMESSAGE_ENUMATTACHTYPE']._serialized_start=363
  _globals['_MEDIAMESSAGE_ENUMATTACHTYPE']._serialized_end=413
  _globals['_VISIBLEMESSAGE']._serialized_start=415
  _globals['_VISIBLEMESSAGE']._serialized_end=466
  _globals['_POIMESSAGE']._serialized_start=468
  _globals['_POIMESSAGE']._serialized_end=554
# @@protoc_insertion_point(module_scope)
