# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WPostDeviceInfoNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WPostDeviceInfoNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bWPostDeviceInfoNotice.proto\x12\x10Im.Scrm.Ww.Proto\"\xa2\x03\n\x1bPostDeviceInfoNoticeMessage\x12\x12\n\nPhoneBrand\x18\x01 \x01(\t\x12\x12\n\nPhoneModel\x18\x02 \x01(\t\x12\x13\n\x0bOSVerNumber\x18\x03 \x01(\x05\x12T\n\x08\x41ppInfos\x18\x04 \x03(\x0b\x32\x42.Im.Scrm.Ww.Proto.PostDeviceInfoNoticeMessage.DeviceAppInfoMessage\x12\x0f\n\x07NetType\x18\x05 \x01(\t\x12\x0c\n\x04WxId\x18\x06 \x01(\x03\x12\x0c\n\x04IMEI\x18\x07 \x01(\t\x12\r\n\x05IMSI1\x18\x08 \x01(\t\x12\r\n\x05IMSI2\x18\t \x01(\t\x12\x0f\n\x07Number1\x18\n \x01(\t\x12\x0f\n\x07Number2\x18\x0b \x01(\t\x12\x0e\n\x06IsHook\x18\x0c \x01(\x08\x12\x11\n\tWxSupport\x18\r \x01(\x08\x1a`\n\x14\x44\x65viceAppInfoMessage\x12\x13\n\x0bPackageName\x18\x01 \x01(\t\x12\x0f\n\x07\x41ppName\x18\x02 \x01(\t\x12\x11\n\tVerNumber\x18\x03 \x01(\x05\x12\x0f\n\x07Version\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WPostDeviceInfoNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTDEVICEINFONOTICEMESSAGE']._serialized_start=50
  _globals['_POSTDEVICEINFONOTICEMESSAGE']._serialized_end=468
  _globals['_POSTDEVICEINFONOTICEMESSAGE_DEVICEAPPINFOMESSAGE']._serialized_start=372
  _globals['_POSTDEVICEINFONOTICEMESSAGE_DEVICEAPPINFOMESSAGE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
