"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PostSnsTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    MEDIA_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    VISIBLE_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    POI_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Content: builtins.str
    """发布的文案"""
    Comment: builtins.str
    """评论 TODO: 暂未实现"""
    TaskId: builtins.int
    """任务id 在TaskResult中回传"""
    @property
    def Media(self) -> global___MediaMessage:
        """携带的图片、视频、链接等资源"""

    @property
    def Visible(self) -> global___VisibleMessage:
        """可见范围"""

    @property
    def Poi(self) -> global___PoiMessage:
        """地理信息 TODO: 暂未实现"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Content: builtins.str = ...,
        Media: global___MediaMessage | None = ...,
        Comment: builtins.str = ...,
        Visible: global___VisibleMessage | None = ...,
        TaskId: builtins.int = ...,
        Poi: global___PoiMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Media", b"Media", "Poi", b"Poi", "Visible", b"Visible"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Comment", b"Comment", "Content", b"Content", "Media", b"Media", "Poi", b"Poi", "TaskId", b"TaskId", "Visible", b"Visible", "WxId", b"WxId"]) -> None: ...

global___PostSnsTaskMessage = PostSnsTaskMessage

@typing.final
class MediaMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _EnumAttachType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _EnumAttachTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[MediaMessage._EnumAttachType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        Picture: MediaMessage._EnumAttachType.ValueType  # 0
        """图片"""
        Video: MediaMessage._EnumAttachType.ValueType  # 1
        """短视频"""
        Link: MediaMessage._EnumAttachType.ValueType  # 2
        """链接"""

    class EnumAttachType(_EnumAttachType, metaclass=_EnumAttachTypeEnumTypeWrapper):
        """附件类型"""

    Picture: MediaMessage.EnumAttachType.ValueType  # 0
    """图片"""
    Video: MediaMessage.EnumAttachType.ValueType  # 1
    """短视频"""
    Link: MediaMessage.EnumAttachType.ValueType  # 2
    """链接"""

    TYPE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    Type: global___MediaMessage.EnumAttachType.ValueType
    """附件类型"""
    @property
    def Content(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """资源url，注意次序！[视频url,缩略图url]；[图片url,图片url,..]；[链接url;标题;图片url]"""

    def __init__(
        self,
        *,
        Type: global___MediaMessage.EnumAttachType.ValueType = ...,
        Content: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Content", b"Content", "Type", b"Type"]) -> None: ...

global___MediaMessage = MediaMessage

@typing.final
class VisibleMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERIDS_FIELD_NUMBER: builtins.int
    LABELIDS_FIELD_NUMBER: builtins.int
    @property
    def userIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def labelIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        userIds: collections.abc.Iterable[builtins.int] | None = ...,
        labelIds: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["labelIds", b"labelIds", "userIds", b"userIds"]) -> None: ...

global___VisibleMessage = VisibleMessage

@typing.final
class PoiMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CITY_FIELD_NUMBER: builtins.int
    ADDRESS_FIELD_NUMBER: builtins.int
    POINAME_FIELD_NUMBER: builtins.int
    LON_FIELD_NUMBER: builtins.int
    LAT_FIELD_NUMBER: builtins.int
    City: builtins.str
    """城市"""
    Address: builtins.str
    """地址"""
    PoiName: builtins.str
    """显示的名称"""
    Lon: builtins.float
    """经度"""
    Lat: builtins.float
    """纬度"""
    def __init__(
        self,
        *,
        City: builtins.str = ...,
        Address: builtins.str = ...,
        PoiName: builtins.str = ...,
        Lon: builtins.float = ...,
        Lat: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Address", b"Address", "City", b"City", "Lat", b"Lat", "Lon", b"Lon", "PoiName", b"PoiName"]) -> None: ...

global___PoiMessage = PoiMessage
