"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PullMySnsListTaskResultNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    SNSLIST_FIELD_NUMBER: builtins.int
    NEXTSEQ_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Success: builtins.bool
    """是否成功"""
    ErrMsg: builtins.str
    """错误内容描述 获取 成功时附带的结果内容"""
    NextSeq: builtins.int
    """下一页起始Seq"""
    TaskId: builtins.int
    @property
    def SnsList(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SnsInfoMessage]: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Success: builtins.bool = ...,
        ErrMsg: builtins.str = ...,
        SnsList: collections.abc.Iterable[global___SnsInfoMessage] | None = ...,
        NextSeq: builtins.int = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ErrMsg", b"ErrMsg", "NextSeq", b"NextSeq", "SnsList", b"SnsList", "Success", b"Success", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___PullMySnsListTaskResultNoticeMessage = PullMySnsListTaskResultNoticeMessage

@typing.final
class SnsInfoMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHOR_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    IMAGES_FIELD_NUMBER: builtins.int
    LINK_FIELD_NUMBER: builtins.int
    VIDEO_FIELD_NUMBER: builtins.int
    COMMENTS_FIELD_NUMBER: builtins.int
    LIKES_FIELD_NUMBER: builtins.int
    SNSID_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    POSTID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    Author: builtins.int
    Content: builtins.str
    SnsId: builtins.int
    Time: builtins.int
    PostId: builtins.str
    Type: builtins.int
    """0 员工发表，2 企业发表"""
    @property
    def Images(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SnsMediaInfoMessage]: ...
    @property
    def Link(self) -> global___SnsMediaInfoMessage: ...
    @property
    def Video(self) -> global___SnsMediaInfoMessage: ...
    @property
    def Comments(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SnsCommentMessage]: ...
    @property
    def Likes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SnsLikeMessage]: ...
    def __init__(
        self,
        *,
        Author: builtins.int = ...,
        Content: builtins.str = ...,
        Images: collections.abc.Iterable[global___SnsMediaInfoMessage] | None = ...,
        Link: global___SnsMediaInfoMessage | None = ...,
        Video: global___SnsMediaInfoMessage | None = ...,
        Comments: collections.abc.Iterable[global___SnsCommentMessage] | None = ...,
        Likes: collections.abc.Iterable[global___SnsLikeMessage] | None = ...,
        SnsId: builtins.int = ...,
        Time: builtins.int = ...,
        PostId: builtins.str = ...,
        Type: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Link", b"Link", "Video", b"Video"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Author", b"Author", "Comments", b"Comments", "Content", b"Content", "Images", b"Images", "Likes", b"Likes", "Link", b"Link", "PostId", b"PostId", "SnsId", b"SnsId", "Time", b"Time", "Type", b"Type", "Video", b"Video"]) -> None: ...

global___SnsInfoMessage = SnsInfoMessage

@typing.final
class SnsMediaInfoMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    THUMBIMG_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    DESC_FIELD_NUMBER: builtins.int
    ThumbImg: builtins.str
    """缩略图地址"""
    Url: builtins.str
    """大图地址，链接地址 视频地址等"""
    Desc: builtins.str
    """描述，标题等"""
    def __init__(
        self,
        *,
        ThumbImg: builtins.str = ...,
        Url: builtins.str = ...,
        Desc: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Desc", b"Desc", "ThumbImg", b"ThumbImg", "Url", b"Url"]) -> None: ...

global___SnsMediaInfoMessage = SnsMediaInfoMessage

@typing.final
class SnsCommentMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRIENDID_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    COMMENTID_FIELD_NUMBER: builtins.int
    REPLYCOMMENTID_FIELD_NUMBER: builtins.int
    REPLYWXID_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    POSTID_FIELD_NUMBER: builtins.int
    FriendId: builtins.int
    """评论人的微信号"""
    Content: builtins.str
    """评论内容"""
    CommentId: builtins.int
    """微信本地数据库的id"""
    ReplyCommentId: builtins.int
    """回复的微信本地数据库的id"""
    ReplyWxId: builtins.int
    """评论对象的微信号"""
    Time: builtins.int
    """评论时间"""
    PostId: builtins.str
    def __init__(
        self,
        *,
        FriendId: builtins.int = ...,
        Content: builtins.str = ...,
        CommentId: builtins.int = ...,
        ReplyCommentId: builtins.int = ...,
        ReplyWxId: builtins.int = ...,
        Time: builtins.int = ...,
        PostId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["CommentId", b"CommentId", "Content", b"Content", "FriendId", b"FriendId", "PostId", b"PostId", "ReplyCommentId", b"ReplyCommentId", "ReplyWxId", b"ReplyWxId", "Time", b"Time"]) -> None: ...

global___SnsCommentMessage = SnsCommentMessage

@typing.final
class SnsLikeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FRIENDID_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    FriendId: builtins.int
    Time: builtins.int
    def __init__(
        self,
        *,
        FriendId: builtins.int = ...,
        Time: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["FriendId", b"FriendId", "Time", b"Time"]) -> None: ...

global___SnsLikeMessage = SnsLikeMessage
