# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WPullMySnsListTaskResultNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WPullMySnsListTaskResultNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$WPullMySnsListTaskResultNotice.proto\x12\x10Im.Scrm.Ww.Proto\"\xa9\x01\n$PullMySnsListTaskResultNoticeMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x0f\n\x07Success\x18\x02 \x01(\x08\x12\x0e\n\x06\x45rrMsg\x18\x03 \x01(\t\x12\x31\n\x07SnsList\x18\x04 \x03(\x0b\x32 .Im.Scrm.Ww.Proto.SnsInfoMessage\x12\x0f\n\x07NextSeq\x18\x05 \x01(\x03\x12\x0e\n\x06TaskId\x18\x06 \x01(\x03\"\xf6\x02\n\x0eSnsInfoMessage\x12\x0e\n\x06\x41uthor\x18\x01 \x01(\x03\x12\x0f\n\x07\x43ontent\x18\x02 \x01(\t\x12\x35\n\x06Images\x18\x03 \x03(\x0b\x32%.Im.Scrm.Ww.Proto.SnsMediaInfoMessage\x12\x33\n\x04Link\x18\x04 \x01(\x0b\x32%.Im.Scrm.Ww.Proto.SnsMediaInfoMessage\x12\x34\n\x05Video\x18\x05 \x01(\x0b\x32%.Im.Scrm.Ww.Proto.SnsMediaInfoMessage\x12\x35\n\x08\x43omments\x18\x06 \x03(\x0b\x32#.Im.Scrm.Ww.Proto.SnsCommentMessage\x12/\n\x05Likes\x18\x07 \x03(\x0b\x32 .Im.Scrm.Ww.Proto.SnsLikeMessage\x12\r\n\x05SnsId\x18\x08 \x01(\x03\x12\x0c\n\x04Time\x18\t \x01(\x05\x12\x0e\n\x06PostId\x18\n \x01(\t\x12\x0c\n\x04Type\x18\x0b \x01(\x05\"B\n\x13SnsMediaInfoMessage\x12\x10\n\x08ThumbImg\x18\x01 \x01(\t\x12\x0b\n\x03Url\x18\x02 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x03 \x01(\t\"\x92\x01\n\x11SnsCommentMessage\x12\x10\n\x08\x46riendId\x18\x01 \x01(\x03\x12\x0f\n\x07\x43ontent\x18\x02 \x01(\t\x12\x11\n\tCommentId\x18\x03 \x01(\x03\x12\x16\n\x0eReplyCommentId\x18\x04 \x01(\x03\x12\x11\n\tReplyWxId\x18\x05 \x01(\x03\x12\x0c\n\x04Time\x18\x06 \x01(\x05\x12\x0e\n\x06PostId\x18\x07 \x01(\t\"0\n\x0eSnsLikeMessage\x12\x10\n\x08\x46riendId\x18\x01 \x01(\x03\x12\x0c\n\x04Time\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WPullMySnsListTaskResultNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PULLMYSNSLISTTASKRESULTNOTICEMESSAGE']._serialized_start=59
  _globals['_PULLMYSNSLISTTASKRESULTNOTICEMESSAGE']._serialized_end=228
  _globals['_SNSINFOMESSAGE']._serialized_start=231
  _globals['_SNSINFOMESSAGE']._serialized_end=605
  _globals['_SNSMEDIAINFOMESSAGE']._serialized_start=607
  _globals['_SNSMEDIAINFOMESSAGE']._serialized_end=673
  _globals['_SNSCOMMENTMESSAGE']._serialized_start=676
  _globals['_SNSCOMMENTMESSAGE']._serialized_end=822
  _globals['_SNSLIKEMESSAGE']._serialized_start=824
  _globals['_SNSLIKEMESSAGE']._serialized_end=872
# @@protoc_insertion_point(module_scope)
