# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WPullSnsTaskListTaskResultNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WPullSnsTaskListTaskResultNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WPullMySnsListTaskResultNotice_pb2 as WPullMySnsListTaskResultNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&WPullSnsTaskListTaskResultNotice.proto\x12\x10Im.Scrm.Ww.Proto\x1a$WPullMySnsListTaskResultNotice.proto\"\x9b\x01\n&PullSnsTaskListTaskResultNoticeMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x0f\n\x07Success\x18\x02 \x01(\x08\x12\x0e\n\x06\x45rrMsg\x18\x03 \x01(\t\x12\x32\n\x08TaskList\x18\x04 \x03(\x0b\x32 .Im.Scrm.Ww.Proto.SnsTaskMessage\x12\x0e\n\x06TaskId\x18\x06 \x01(\x03\"c\n\x0eSnsTaskMessage\x12\x0e\n\x06\x41uthor\x18\x01 \x01(\x03\x12\x31\n\x07SnsInfo\x18\x02 \x01(\x0b\x32 .Im.Scrm.Ww.Proto.SnsInfoMessage\x12\x0e\n\x06Posted\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WPullSnsTaskListTaskResultNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PULLSNSTASKLISTTASKRESULTNOTICEMESSAGE']._serialized_start=99
  _globals['_PULLSNSTASKLISTTASKRESULTNOTICEMESSAGE']._serialized_end=254
  _globals['_SNSTASKMESSAGE']._serialized_start=256
  _globals['_SNSTASKMESSAGE']._serialized_end=355
# @@protoc_insertion_point(module_scope)
