"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WPullMySnsListTaskResultNotice_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PullSnsTaskListTaskResultNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    TASKLIST_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Success: builtins.bool
    """是否成功"""
    ErrMsg: builtins.str
    """错误内容描述 获取 成功时附带的结果内容"""
    TaskId: builtins.int
    @property
    def TaskList(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SnsTaskMessage]: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Success: builtins.bool = ...,
        ErrMsg: builtins.str = ...,
        TaskList: collections.abc.Iterable[global___SnsTaskMessage] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ErrMsg", b"ErrMsg", "Success", b"Success", "TaskId", b"TaskId", "TaskList", b"TaskList", "WxId", b"WxId"]) -> None: ...

global___PullSnsTaskListTaskResultNoticeMessage = PullSnsTaskListTaskResultNoticeMessage

@typing.final
class SnsTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHOR_FIELD_NUMBER: builtins.int
    SNSINFO_FIELD_NUMBER: builtins.int
    POSTED_FIELD_NUMBER: builtins.int
    Author: builtins.int
    Posted: builtins.bool
    """是否已发表"""
    @property
    def SnsInfo(self) -> WPullMySnsListTaskResultNotice_pb2.SnsInfoMessage: ...
    def __init__(
        self,
        *,
        Author: builtins.int = ...,
        SnsInfo: WPullMySnsListTaskResultNotice_pb2.SnsInfoMessage | None = ...,
        Posted: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["SnsInfo", b"SnsInfo"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Author", b"Author", "Posted", b"Posted", "SnsInfo", b"SnsInfo"]) -> None: ...

global___SnsTaskMessage = SnsTaskMessage
