"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class RedirectNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    SERVERURL_FIELD_NUMBER: builtins.int
    SERVERPORT_FIELD_NUMBER: builtins.int
    Type: builtins.int
    """类型，0：临时变更，1：永久变更"""
    ServerUrl: builtins.str
    """业务服务器地址"""
    ServerPort: builtins.int
    """业务服务器端口"""
    def __init__(
        self,
        *,
        Type: builtins.int = ...,
        ServerUrl: builtins.str = ...,
        ServerPort: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ServerPort", b"ServerPort", "ServerUrl", b"ServerUrl", "Type", b"Type"]) -> None: ...

global___RedirectNoticeMessage = RedirectNoticeMessage
