# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WSearchMsgTaskResultNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WSearchMsgTaskResultNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WHistoryMsgPushNotice_pb2 as WHistoryMsgPushNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n WSearchMsgTaskResultNotice.proto\x12\x10Im.Scrm.Ww.Proto\x1a\x1bWHistoryMsgPushNotice.proto\"W\n\x0b\x43onvMessage\x12\n\n\x02Id\x18\x01 \x01(\x03\x12\x10\n\x08RemoteId\x18\x02 \x01(\x03\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0e\n\x06\x41vatar\x18\x04 \x01(\t\x12\x0c\n\x04Type\x18\x05 \x01(\x05\"h\n\x0cSearchResult\x12+\n\x04\x63onv\x18\x01 \x01(\x0b\x32\x1d.Im.Scrm.Ww.Proto.ConvMessage\x12+\n\x04Msgs\x18\x02 \x03(\x0b\x32\x1d.Im.Scrm.Ww.Proto.ChatMessage\"\xa3\x01\n SearchMsgTaskResultNoticeMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x0f\n\x07Keyword\x18\x02 \x01(\t\x12\x0f\n\x07Success\x18\x03 \x01(\x08\x12\x0e\n\x06\x45rrMsg\x18\x04 \x01(\t\x12/\n\x07Results\x18\x05 \x03(\x0b\x32\x1e.Im.Scrm.Ww.Proto.SearchResult\x12\x0e\n\x06TaskId\x18\x06 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WSearchMsgTaskResultNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONVMESSAGE']._serialized_start=83
  _globals['_CONVMESSAGE']._serialized_end=170
  _globals['_SEARCHRESULT']._serialized_start=172
  _globals['_SEARCHRESULT']._serialized_end=276
  _globals['_SEARCHMSGTASKRESULTNOTICEMESSAGE']._serialized_start=279
  _globals['_SEARCHMSGTASKRESULTNOTICEMESSAGE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
