"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WHistoryMsgPushNotice_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ConvMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    REMOTEID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    AVATAR_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    Id: builtins.int
    """"""
    RemoteId: builtins.int
    """单聊=联系人RemoteId, 群聊=公司id，部门id或其他"""
    Name: builtins.str
    Avatar: builtins.str
    Type: builtins.int
    """0 单聊 1 群聊"""
    def __init__(
        self,
        *,
        Id: builtins.int = ...,
        RemoteId: builtins.int = ...,
        Name: builtins.str = ...,
        Avatar: builtins.str = ...,
        Type: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Avatar", b"Avatar", "Id", b"Id", "Name", b"Name", "RemoteId", b"RemoteId", "Type", b"Type"]) -> None: ...

global___ConvMessage = ConvMessage

@typing.final
class SearchResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONV_FIELD_NUMBER: builtins.int
    MSGS_FIELD_NUMBER: builtins.int
    @property
    def conv(self) -> global___ConvMessage: ...
    @property
    def Msgs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[WHistoryMsgPushNotice_pb2.ChatMessage]: ...
    def __init__(
        self,
        *,
        conv: global___ConvMessage | None = ...,
        Msgs: collections.abc.Iterable[WHistoryMsgPushNotice_pb2.ChatMessage] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["conv", b"conv"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Msgs", b"Msgs", "conv", b"conv"]) -> None: ...

global___SearchResult = SearchResult

@typing.final
class SearchMsgTaskResultNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    KEYWORD_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    RESULTS_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Keyword: builtins.str
    """"""
    Success: builtins.bool
    """"""
    ErrMsg: builtins.str
    TaskId: builtins.int
    @property
    def Results(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SearchResult]: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Keyword: builtins.str = ...,
        Success: builtins.bool = ...,
        ErrMsg: builtins.str = ...,
        Results: collections.abc.Iterable[global___SearchResult] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ErrMsg", b"ErrMsg", "Keyword", b"Keyword", "Results", b"Results", "Success", b"Success", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___SearchMsgTaskResultNoticeMessage = SearchMsgTaskResultNoticeMessage
