"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SnsCommentTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    SNSID_FIELD_NUMBER: builtins.int
    POSTID_FIELD_NUMBER: builtins.int
    COMMENT_FIELD_NUMBER: builtins.int
    REFWXID_FIELD_NUMBER: builtins.int
    REFCOMMENTID_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    SnsId: builtins.int
    """朋友圈id"""
    PostId: builtins.str
    """朋友圈postid"""
    Comment: builtins.str
    """评论"""
    RefWxId: builtins.int
    """回复的好友id"""
    RefCommentId: builtins.int
    """回复的评论id"""
    TaskId: builtins.int
    """任务id 在TaskResult中回传"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        SnsId: builtins.int = ...,
        PostId: builtins.str = ...,
        Comment: builtins.str = ...,
        RefWxId: builtins.int = ...,
        RefCommentId: builtins.int = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Comment", b"Comment", "PostId", b"PostId", "RefCommentId", b"RefCommentId", "RefWxId", b"RefWxId", "SnsId", b"SnsId", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___SnsCommentTaskMessage = SnsCommentTaskMessage
