"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SnsMsgNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    SNSID_FIELD_NUMBER: builtins.int
    FRIENDID_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    COMMENTID_FIELD_NUMBER: builtins.int
    REPLYCOMMENTID_FIELD_NUMBER: builtins.int
    REPLYWXID_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    POSTID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Type: builtins.int
    """类型：1 评论，2 点赞"""
    SnsId: builtins.int
    FriendId: builtins.int
    """评论人的微信号"""
    Content: builtins.str
    """评论内容"""
    CommentId: builtins.int
    """微信本地数据库的id"""
    ReplyCommentId: builtins.int
    """回复的微信本地数据库的id"""
    ReplyWxId: builtins.int
    """评论对象的微信号"""
    Time: builtins.int
    """评论时间"""
    PostId: builtins.str
    """sns postid"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Type: builtins.int = ...,
        SnsId: builtins.int = ...,
        FriendId: builtins.int = ...,
        Content: builtins.str = ...,
        CommentId: builtins.int = ...,
        ReplyCommentId: builtins.int = ...,
        ReplyWxId: builtins.int = ...,
        Time: builtins.int = ...,
        PostId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["CommentId", b"CommentId", "Content", b"Content", "FriendId", b"FriendId", "PostId", b"PostId", "ReplyCommentId", b"ReplyCommentId", "ReplyWxId", b"ReplyWxId", "SnsId", b"SnsId", "Time", b"Time", "Type", b"Type", "WxId", b"WxId"]) -> None: ...

global___SnsMsgNoticeMessage = SnsMsgNoticeMessage
