"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WPullMySnsListTaskResultNotice_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SnsNotifyNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    SNSINFO_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Content: builtins.str
    """错误内容描述 获取 成功时附带的结果内容"""
    Type: builtins.int
    @property
    def SnsInfo(self) -> WPullMySnsListTaskResultNotice_pb2.SnsInfoMessage: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Content: builtins.str = ...,
        SnsInfo: WPullMySnsListTaskResultNotice_pb2.SnsInfoMessage | None = ...,
        Type: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["SnsInfo", b"SnsInfo"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["Content", b"Content", "SnsInfo", b"SnsInfo", "Type", b"Type", "WxId", b"WxId"]) -> None: ...

global___SnsNotifyNoticeMessage = SnsNotifyNoticeMessage
