# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WTalkToFriendTask.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WTalkToFriendTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WTransport_pb2 as WTransport__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17WTalkToFriendTask.proto\x12\x10Im.Scrm.Ww.Proto\x1a\x10WTransport.proto\"\xc3\x01\n\x17TalkToFriendTaskMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x0e\n\x06\x43onvId\x18\x02 \x01(\x03\x12\x0f\n\x07LocalId\x18\x03 \x01(\x03\x12\x36\n\x0b\x43ontentType\x18\x04 \x01(\x0e\x32!.Im.Scrm.Ww.Proto.EnumContentType\x12\x0f\n\x07\x43ontent\x18\x05 \x01(\x0c\x12\r\n\x05RefId\x18\x06 \x01(\x03\x12\x11\n\tAtSomeOne\x18\x07 \x03(\x03\x12\x0e\n\x06TaskId\x18\t \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WTalkToFriendTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TALKTOFRIENDTASKMESSAGE']._serialized_start=64
  _globals['_TALKTOFRIENDTASKMESSAGE']._serialized_end=259
# @@protoc_insertion_point(module_scope)
