"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WTransport_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TalkToFriendTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONVID_FIELD_NUMBER: builtins.int
    LOCALID_FIELD_NUMBER: builtins.int
    CONTENTTYPE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    REFID_FIELD_NUMBER: builtins.int
    ATSOMEONE_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    ConvId: builtins.int
    """会话 RemoteId"""
    LocalId: builtins.int
    """会话id"""
    ContentType: WTransport_pb2.EnumContentType.ValueType
    """消息类型 Text Picture Voice Video Link File NameCard WeApp Location Quote"""
    Content: builtins.bytes
    """消息内容 文本，url（图片 视频 语音 文件），名片wxid，json(语音 文件 链接 小程序 位置)"""
    RefId: builtins.int
    """引用消息id"""
    TaskId: builtins.int
    """发送给手机端的时候需要赋值，"""
    @property
    def AtSomeOne(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """群聊@某人 0表示@所有人"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        ConvId: builtins.int = ...,
        LocalId: builtins.int = ...,
        ContentType: WTransport_pb2.EnumContentType.ValueType = ...,
        Content: builtins.bytes = ...,
        RefId: builtins.int = ...,
        AtSomeOne: collections.abc.Iterable[builtins.int] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AtSomeOne", b"AtSomeOne", "Content", b"Content", "ContentType", b"ContentType", "ConvId", b"ConvId", "LocalId", b"LocalId", "RefId", b"RefId", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___TalkToFriendTaskMessage = TalkToFriendTaskMessage
