"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WTransport_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TaskResultNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    TASKTYPE_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    CODE_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    EXT_FIELD_NUMBER: builtins.int
    EXTID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    TaskType: WTransport_pb2.EnumMsgType.ValueType
    """原来执行的任务的类型"""
    TaskId: builtins.int
    """业务的id,通用的。"""
    Success: builtins.bool
    """是否成功"""
    Code: WTransport_pb2.EnumErrorCode.ValueType
    """错误码 Success = true 忽略"""
    ErrMsg: builtins.str
    """错误内容描述"""
    Ext: builtins.str
    """自定义返回数据 string"""
    ExtId: builtins.int
    """自定义返回数据 long"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        TaskType: WTransport_pb2.EnumMsgType.ValueType = ...,
        TaskId: builtins.int = ...,
        Success: builtins.bool = ...,
        Code: WTransport_pb2.EnumErrorCode.ValueType = ...,
        ErrMsg: builtins.str = ...,
        Ext: builtins.str = ...,
        ExtId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Code", b"Code", "ErrMsg", b"ErrMsg", "Ext", b"Ext", "ExtId", b"ExtId", "Success", b"Success", "TaskId", b"TaskId", "TaskType", b"TaskType", "WxId", b"WxId"]) -> None: ...

global___TaskResultNoticeMessage = TaskResultNoticeMessage
