"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _EnumMsgType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EnumMsgTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EnumMsgType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownMsg: _EnumMsgType.ValueType  # 0
    """未知消息"""
    HeartBeatReq: _EnumMsgType.ValueType  # 1001
    """客户端发送的心跳包"""
    MsgReceivedAck: _EnumMsgType.ValueType  # 1002
    """消息接收确认回复（接收或拒绝接收）"""
    Error: _EnumMsgType.ValueType  # 1003
    """将错误单独提升为一种消息类型"""
    DeviceAuthReq: _EnumMsgType.ValueType  # 1010
    """设备客户端授权类消息
    设备(手机客户端、客服客户端)获取通信token请求
    """
    DeviceAuthRsp: _EnumMsgType.ValueType  # 1011
    """设备(手机客户端、客服客户端)获取通信token响应"""
    DeviceExitNotice: _EnumMsgType.ValueType  # 1012
    """设备授权后退出(仅用于服务端内部)"""
    AccountForceOfflineNotice: _EnumMsgType.ValueType  # 1013
    """账号强制下线通知"""
    RedirectNotice: _EnumMsgType.ValueType  # 1015
    """服务器重定向"""
    UpgradeDeviceAppNotice: _EnumMsgType.ValueType  # 1016
    """通知手机客户端软件升级"""
    TriggerDeviceInfo: _EnumMsgType.ValueType  # 1017
    DeviceAuthResult: _EnumMsgType.ValueType  # 1018
    PhoneActionTask: _EnumMsgType.ValueType  # 1020
    """通知手机端执行特定任务"""
    GetWeChatsReq: _EnumMsgType.ValueType  # 1021
    GetWeChatsResp: _EnumMsgType.ValueType  # 1022
    ConfigPushNotice: _EnumMsgType.ValueType  # 1030
    ConfigSetting: _EnumMsgType.ValueType  # 1031
    WwOnlineNotice: _EnumMsgType.ValueType  # 1100
    """手机客户端上传的通知类消息
    手机客户端微信上线通知
    """
    WwOfflineNotice: _EnumMsgType.ValueType  # 1101
    """手机客户端微信下线通知"""
    PostDeviceInfoNotice: _EnumMsgType.ValueType  # 1104
    """手机端信息推送
    手机端推送当前安装版本
    """
    ContactPushNotice: _EnumMsgType.ValueType  # 1105
    """手机端推送联系人列表"""
    DepartmentPushNotice: _EnumMsgType.ValueType  # 1106
    """手机端推送部门信息列表"""
    CustomerPushNotice: _EnumMsgType.ValueType  # 1107
    """手机端推送客户联系人"""
    UserLabelPushNotice: _EnumMsgType.ValueType  # 1108
    """推送客户标签"""
    CorporationPushNotice: _EnumMsgType.ValueType  # 1109
    """推送客户公司信息"""
    ConversationPushNotice: _EnumMsgType.ValueType  # 1110
    """推送聊天会话（包含群聊信息）"""
    NewCustomerPushNotice: _EnumMsgType.ValueType  # 1111
    """手机端推送新客户列表"""
    NewCustomerAddedNotice: _EnumMsgType.ValueType  # 1112
    """新客户变更通知"""
    CustomerAddNotice: _EnumMsgType.ValueType  # 1113
    """客户新增"""
    CustomerDelNotice: _EnumMsgType.ValueType  # 1114
    """客户删除"""
    UserLabelChangedNotice: _EnumMsgType.ValueType  # 1115
    """客户标签变化推送，"""
    DepartmentChangedNotice: _EnumMsgType.ValueType  # 1116
    """部门信息变化推送，未实现"""
    ConversationAddNotice: _EnumMsgType.ValueType  # 1117
    """会话新增通知"""
    WxFriendPushNotice: _EnumMsgType.ValueType  # 1118
    """微信好友列表推送，用于从微信好友中添加客户"""
    PostMessageReadNotice: _EnumMsgType.ValueType  # 1119
    """手机上消息已读"""
    FriendTalkNotice: _EnumMsgType.ValueType  # 1120
    """微信好友发来聊天消息"""
    TalkToFriendNotice: _EnumMsgType.ValueType  # 1121
    """手机上回复好友的聊天消息"""
    TaskResultNotice: _EnumMsgType.ValueType  # 1122
    """任务执行结果通知"""
    TalkToFriendTaskResultNotice: _EnumMsgType.ValueType  # 1123
    """手机端向服务端通知聊天执行结果"""
    DownloadFileResultNotice: _EnumMsgType.ValueType  # 1124
    """文件下载任务或手机端自动下载结果推送"""
    PullMyQrCodeTaskResultNotice: _EnumMsgType.ValueType  # 1125
    """获取二维码结果推送"""
    ConversationChangedNotice: _EnumMsgType.ValueType  # 1126
    """会话变更通知"""
    HistoryMsgPushNotice: _EnumMsgType.ValueType  # 1127
    """消息记录通知"""
    PullMySnsListTaskResultNotice: _EnumMsgType.ValueType  # 1128
    """获取我的朋友圈列表结果返回"""
    PullSnsTaskListTaskResultNotice: _EnumMsgType.ValueType  # 1129
    """获取企业发布的朋友圈任务结果返回"""
    PostSnsTaskResultNotice: _EnumMsgType.ValueType  # 1130
    """发朋友圈结果返回 TODO: 目前snsId未获得，后期优化"""
    SnsCommentTaskResultNotice: _EnumMsgType.ValueType  # 1131
    """朋友圈评论结果返回 TODO: 评论id未获得，后期优化"""
    GetSnsDataTaskResultNotice: _EnumMsgType.ValueType  # 1132
    """获取单个朋友圈结果返回"""
    SnsNotifyNotice: _EnumMsgType.ValueType  # 1133
    """企业朋友圈通知消息 主要为管理员发布朋友圈任务给成员"""
    UserLabelModifyTaskResultNotice: _EnumMsgType.ValueType  # 1134
    """新增或修改个人标签结果返回"""
    GetContactInfoTaskResultNotice: _EnumMsgType.ValueType  # 1135
    PhoneStateTaskResultNotice: _EnumMsgType.ValueType  # 1136
    """手机状态结果返回"""
    PhoneStateWarningNotice: _EnumMsgType.ValueType  # 1137
    """手机状态告警提示"""
    MsgRevokeNotice: _EnumMsgType.ValueType  # 1138
    """消息撤回通知"""
    SearchMsgTaskResultNotice: _EnumMsgType.ValueType  # 1139
    SnsMsgNotice: _EnumMsgType.ValueType  # 1140
    GroupMemberPushNotice: _EnumMsgType.ValueType  # 1141
    """群成员信息返回"""
    AddEmojiTaskResultNotice: _EnumMsgType.ValueType  # 1142
    """添加自定义表情结果返回"""
    VoiceTextNotice: _EnumMsgType.ValueType  # 1143
    """语音消息转文字内容推送"""
    CustomerGroupPushNotice: _EnumMsgType.ValueType  # 1150
    """推送客户群"""
    GroupMemberAddNotice: _EnumMsgType.ValueType  # 1151
    """入群通知"""
    GroupMemberDelNotice: _EnumMsgType.ValueType  # 1152
    """退群通知"""
    ConversationInfoNotice: _EnumMsgType.ValueType  # 1153
    """会话信息"""
    OneWayCustomerPushNotice: _EnumMsgType.ValueType  # 1155
    """单向客户id"""
    TriggerAccountPushTask: _EnumMsgType.ValueType  # 1200
    """推送给手机端的任务
    触发手机推送微信账号登陆信息
    """
    TriggerContactPushTask: _EnumMsgType.ValueType  # 1201
    """触发手机推送联系人列表任务"""
    TriggerCustomerPushTask: _EnumMsgType.ValueType  # 1202
    """触发手机推送客户列表任务"""
    TriggerConversationPushTask: _EnumMsgType.ValueType  # 1203
    """触发手机推送会话列表任务"""
    TriggerWechatFriendPushTask: _EnumMsgType.ValueType  # 1204
    """触发手机推送微信好友列表任务"""
    TriggerHistoryMsgPushTask: _EnumMsgType.ValueType  # 1205
    """通知手机推送聊天记录"""
    TriggerMessageReadTask: _EnumMsgType.ValueType  # 1206
    """通知手机将某个聊天窗口置为已读"""
    TriggerUserLabelTask: _EnumMsgType.ValueType  # 1207
    """触发手机推送客户标签"""
    TriggerNewCustomerTask: _EnumMsgType.ValueType  # 1208
    """触发手机推送新客户"""
    TriggerCustomerGroupTask: _EnumMsgType.ValueType  # 1209
    """触发手机推送客户群"""
    TalkToFriendTask: _EnumMsgType.ValueType  # 1210
    """给好友发消息任务"""
    DownloadFileByUrlTask: _EnumMsgType.ValueType  # 1211
    """通过url和authkey下载文件（图片，视频）"""
    DownloadFileByMsgIdTask: _EnumMsgType.ValueType  # 1212
    """通过消息Id下载文件（图片，视频）"""
    AddCustomerFromWxTask: _EnumMsgType.ValueType  # 1214
    """添加客户-从微信好友中添加"""
    AddCustomerFromSearchTask: _EnumMsgType.ValueType  # 1215
    """添加客户-通过手机号搜索添加微信"""
    PullMyQrCodeTask: _EnumMsgType.ValueType  # 1216
    """服务端主动要求手机上传当前账号的二维码"""
    ChatRoomActionTask: _EnumMsgType.ValueType  # 1217
    """群聊管理"""
    PullMySnsListTask: _EnumMsgType.ValueType  # 1218
    """获取我的朋友圈列表"""
    PullSnsTaskListTask: _EnumMsgType.ValueType  # 1219
    """获取企业管理员发布的朋友圈任务"""
    PostSnsTask: _EnumMsgType.ValueType  # 1220
    """发表朋友圈"""
    PostSnsTaskTask: _EnumMsgType.ValueType  # 1221
    """发表企业群发朋友圈"""
    SnsLikeTask: _EnumMsgType.ValueType  # 1222
    """朋友圈点赞"""
    SnsCommentTask: _EnumMsgType.ValueType  # 1223
    """朋友圈评论"""
    DelSnsTask: _EnumMsgType.ValueType  # 1224
    """删除朋友圈"""
    DelSnsCommentTask: _EnumMsgType.ValueType  # 1225
    """删除朋友圈评论"""
    GetSnsDataTask: _EnumMsgType.ValueType  # 1226
    """获取一条朋友圈内容"""
    UserLabelDelTask: _EnumMsgType.ValueType  # 1227
    """删除个人标签"""
    UserLabelModifyTask: _EnumMsgType.ValueType  # 1228
    """新增或修改个人标签"""
    UserLabelSetTask: _EnumMsgType.ValueType  # 1229
    """设置标签任务（基于标签）"""
    AddCustomerByIdTask: _EnumMsgType.ValueType  # 1230
    """通过微信好友的openid添加客户"""
    GetContactInfoTask: _EnumMsgType.ValueType  # 1231
    """获取联系人信息"""
    AcceptCustomerTask: _EnumMsgType.ValueType  # 1232
    """通过新客户验证"""
    UserSetLabelTask: _EnumMsgType.ValueType  # 1233
    """联系人(客户）设置标签（基于客户）开发中"""
    SetUserMemoTask: _EnumMsgType.ValueType  # 1234
    """修改备注 开发中"""
    PhoneStateTask: _EnumMsgType.ValueType  # 1235
    """获取手机状态"""
    MsgRevokeTask: _EnumMsgType.ValueType  # 1236
    """消息撤回"""
    SearchMsgTask: _EnumMsgType.ValueType  # 1237
    """消息搜索"""
    AddCustomerByGroupTask: _EnumMsgType.ValueType  # 1238
    """外部群加客户"""
    ForwardMsgTask: _EnumMsgType.ValueType  # 1239
    """转发消息"""
    ForwardMultiTask: _EnumMsgType.ValueType  # 1240
    """多条转发"""
    GetGroupMemberTask: _EnumMsgType.ValueType  # 1241
    """获取群聊成员信息"""
    AddEmojiTask: _EnumMsgType.ValueType  # 1242
    """添加自定义表情"""
    VoiceTransTextTask: _EnumMsgType.ValueType  # 1243
    """语音消息转文字"""
    JoinGroupInviteTask: _EnumMsgType.ValueType  # 1244
    """加入群邀请"""
    DelCustomerTask: _EnumMsgType.ValueType  # 1245
    """删除客户"""
    SendFriendVerifyTask: _EnumMsgType.ValueType  # 1246
    """发送好友验证"""
    GetConversationInfoTask: _EnumMsgType.ValueType  # 1250
    """请求具体群聊的详细信息"""
    GetExtUserIdTask: _EnumMsgType.ValueType  # 1251
    """获取外部userId"""
    GetExtUserIdTaskResult: _EnumMsgType.ValueType  # 1252
    """获取外部userId返回结果"""
    RunFunCardTask: _EnumMsgType.ValueType  # 1253
    """执行App功能卡片（当前只支持 群发助手的群发通知）"""
    DaKaTask: _EnumMsgType.ValueType  # 1255
    """打卡任务"""

class EnumMsgType(_EnumMsgType, metaclass=_EnumMsgTypeEnumTypeWrapper):
    """消息类型枚举，一般每一个消息类型都应该对应一个特定的message结构
    20xx形式的消息类型需要 手机客户端开发者留意
    30xx形式的消息类型需要 PC客户端开发者留意
    10xx形式的消息类型需要 手机客户端、PC客户端开发者留意
    """

UnknownMsg: EnumMsgType.ValueType  # 0
"""未知消息"""
HeartBeatReq: EnumMsgType.ValueType  # 1001
"""客户端发送的心跳包"""
MsgReceivedAck: EnumMsgType.ValueType  # 1002
"""消息接收确认回复（接收或拒绝接收）"""
Error: EnumMsgType.ValueType  # 1003
"""将错误单独提升为一种消息类型"""
DeviceAuthReq: EnumMsgType.ValueType  # 1010
"""设备客户端授权类消息
设备(手机客户端、客服客户端)获取通信token请求
"""
DeviceAuthRsp: EnumMsgType.ValueType  # 1011
"""设备(手机客户端、客服客户端)获取通信token响应"""
DeviceExitNotice: EnumMsgType.ValueType  # 1012
"""设备授权后退出(仅用于服务端内部)"""
AccountForceOfflineNotice: EnumMsgType.ValueType  # 1013
"""账号强制下线通知"""
RedirectNotice: EnumMsgType.ValueType  # 1015
"""服务器重定向"""
UpgradeDeviceAppNotice: EnumMsgType.ValueType  # 1016
"""通知手机客户端软件升级"""
TriggerDeviceInfo: EnumMsgType.ValueType  # 1017
DeviceAuthResult: EnumMsgType.ValueType  # 1018
PhoneActionTask: EnumMsgType.ValueType  # 1020
"""通知手机端执行特定任务"""
GetWeChatsReq: EnumMsgType.ValueType  # 1021
GetWeChatsResp: EnumMsgType.ValueType  # 1022
ConfigPushNotice: EnumMsgType.ValueType  # 1030
ConfigSetting: EnumMsgType.ValueType  # 1031
WwOnlineNotice: EnumMsgType.ValueType  # 1100
"""手机客户端上传的通知类消息
手机客户端微信上线通知
"""
WwOfflineNotice: EnumMsgType.ValueType  # 1101
"""手机客户端微信下线通知"""
PostDeviceInfoNotice: EnumMsgType.ValueType  # 1104
"""手机端信息推送
手机端推送当前安装版本
"""
ContactPushNotice: EnumMsgType.ValueType  # 1105
"""手机端推送联系人列表"""
DepartmentPushNotice: EnumMsgType.ValueType  # 1106
"""手机端推送部门信息列表"""
CustomerPushNotice: EnumMsgType.ValueType  # 1107
"""手机端推送客户联系人"""
UserLabelPushNotice: EnumMsgType.ValueType  # 1108
"""推送客户标签"""
CorporationPushNotice: EnumMsgType.ValueType  # 1109
"""推送客户公司信息"""
ConversationPushNotice: EnumMsgType.ValueType  # 1110
"""推送聊天会话（包含群聊信息）"""
NewCustomerPushNotice: EnumMsgType.ValueType  # 1111
"""手机端推送新客户列表"""
NewCustomerAddedNotice: EnumMsgType.ValueType  # 1112
"""新客户变更通知"""
CustomerAddNotice: EnumMsgType.ValueType  # 1113
"""客户新增"""
CustomerDelNotice: EnumMsgType.ValueType  # 1114
"""客户删除"""
UserLabelChangedNotice: EnumMsgType.ValueType  # 1115
"""客户标签变化推送，"""
DepartmentChangedNotice: EnumMsgType.ValueType  # 1116
"""部门信息变化推送，未实现"""
ConversationAddNotice: EnumMsgType.ValueType  # 1117
"""会话新增通知"""
WxFriendPushNotice: EnumMsgType.ValueType  # 1118
"""微信好友列表推送，用于从微信好友中添加客户"""
PostMessageReadNotice: EnumMsgType.ValueType  # 1119
"""手机上消息已读"""
FriendTalkNotice: EnumMsgType.ValueType  # 1120
"""微信好友发来聊天消息"""
TalkToFriendNotice: EnumMsgType.ValueType  # 1121
"""手机上回复好友的聊天消息"""
TaskResultNotice: EnumMsgType.ValueType  # 1122
"""任务执行结果通知"""
TalkToFriendTaskResultNotice: EnumMsgType.ValueType  # 1123
"""手机端向服务端通知聊天执行结果"""
DownloadFileResultNotice: EnumMsgType.ValueType  # 1124
"""文件下载任务或手机端自动下载结果推送"""
PullMyQrCodeTaskResultNotice: EnumMsgType.ValueType  # 1125
"""获取二维码结果推送"""
ConversationChangedNotice: EnumMsgType.ValueType  # 1126
"""会话变更通知"""
HistoryMsgPushNotice: EnumMsgType.ValueType  # 1127
"""消息记录通知"""
PullMySnsListTaskResultNotice: EnumMsgType.ValueType  # 1128
"""获取我的朋友圈列表结果返回"""
PullSnsTaskListTaskResultNotice: EnumMsgType.ValueType  # 1129
"""获取企业发布的朋友圈任务结果返回"""
PostSnsTaskResultNotice: EnumMsgType.ValueType  # 1130
"""发朋友圈结果返回 TODO: 目前snsId未获得，后期优化"""
SnsCommentTaskResultNotice: EnumMsgType.ValueType  # 1131
"""朋友圈评论结果返回 TODO: 评论id未获得，后期优化"""
GetSnsDataTaskResultNotice: EnumMsgType.ValueType  # 1132
"""获取单个朋友圈结果返回"""
SnsNotifyNotice: EnumMsgType.ValueType  # 1133
"""企业朋友圈通知消息 主要为管理员发布朋友圈任务给成员"""
UserLabelModifyTaskResultNotice: EnumMsgType.ValueType  # 1134
"""新增或修改个人标签结果返回"""
GetContactInfoTaskResultNotice: EnumMsgType.ValueType  # 1135
PhoneStateTaskResultNotice: EnumMsgType.ValueType  # 1136
"""手机状态结果返回"""
PhoneStateWarningNotice: EnumMsgType.ValueType  # 1137
"""手机状态告警提示"""
MsgRevokeNotice: EnumMsgType.ValueType  # 1138
"""消息撤回通知"""
SearchMsgTaskResultNotice: EnumMsgType.ValueType  # 1139
SnsMsgNotice: EnumMsgType.ValueType  # 1140
GroupMemberPushNotice: EnumMsgType.ValueType  # 1141
"""群成员信息返回"""
AddEmojiTaskResultNotice: EnumMsgType.ValueType  # 1142
"""添加自定义表情结果返回"""
VoiceTextNotice: EnumMsgType.ValueType  # 1143
"""语音消息转文字内容推送"""
CustomerGroupPushNotice: EnumMsgType.ValueType  # 1150
"""推送客户群"""
GroupMemberAddNotice: EnumMsgType.ValueType  # 1151
"""入群通知"""
GroupMemberDelNotice: EnumMsgType.ValueType  # 1152
"""退群通知"""
ConversationInfoNotice: EnumMsgType.ValueType  # 1153
"""会话信息"""
OneWayCustomerPushNotice: EnumMsgType.ValueType  # 1155
"""单向客户id"""
TriggerAccountPushTask: EnumMsgType.ValueType  # 1200
"""推送给手机端的任务
触发手机推送微信账号登陆信息
"""
TriggerContactPushTask: EnumMsgType.ValueType  # 1201
"""触发手机推送联系人列表任务"""
TriggerCustomerPushTask: EnumMsgType.ValueType  # 1202
"""触发手机推送客户列表任务"""
TriggerConversationPushTask: EnumMsgType.ValueType  # 1203
"""触发手机推送会话列表任务"""
TriggerWechatFriendPushTask: EnumMsgType.ValueType  # 1204
"""触发手机推送微信好友列表任务"""
TriggerHistoryMsgPushTask: EnumMsgType.ValueType  # 1205
"""通知手机推送聊天记录"""
TriggerMessageReadTask: EnumMsgType.ValueType  # 1206
"""通知手机将某个聊天窗口置为已读"""
TriggerUserLabelTask: EnumMsgType.ValueType  # 1207
"""触发手机推送客户标签"""
TriggerNewCustomerTask: EnumMsgType.ValueType  # 1208
"""触发手机推送新客户"""
TriggerCustomerGroupTask: EnumMsgType.ValueType  # 1209
"""触发手机推送客户群"""
TalkToFriendTask: EnumMsgType.ValueType  # 1210
"""给好友发消息任务"""
DownloadFileByUrlTask: EnumMsgType.ValueType  # 1211
"""通过url和authkey下载文件（图片，视频）"""
DownloadFileByMsgIdTask: EnumMsgType.ValueType  # 1212
"""通过消息Id下载文件（图片，视频）"""
AddCustomerFromWxTask: EnumMsgType.ValueType  # 1214
"""添加客户-从微信好友中添加"""
AddCustomerFromSearchTask: EnumMsgType.ValueType  # 1215
"""添加客户-通过手机号搜索添加微信"""
PullMyQrCodeTask: EnumMsgType.ValueType  # 1216
"""服务端主动要求手机上传当前账号的二维码"""
ChatRoomActionTask: EnumMsgType.ValueType  # 1217
"""群聊管理"""
PullMySnsListTask: EnumMsgType.ValueType  # 1218
"""获取我的朋友圈列表"""
PullSnsTaskListTask: EnumMsgType.ValueType  # 1219
"""获取企业管理员发布的朋友圈任务"""
PostSnsTask: EnumMsgType.ValueType  # 1220
"""发表朋友圈"""
PostSnsTaskTask: EnumMsgType.ValueType  # 1221
"""发表企业群发朋友圈"""
SnsLikeTask: EnumMsgType.ValueType  # 1222
"""朋友圈点赞"""
SnsCommentTask: EnumMsgType.ValueType  # 1223
"""朋友圈评论"""
DelSnsTask: EnumMsgType.ValueType  # 1224
"""删除朋友圈"""
DelSnsCommentTask: EnumMsgType.ValueType  # 1225
"""删除朋友圈评论"""
GetSnsDataTask: EnumMsgType.ValueType  # 1226
"""获取一条朋友圈内容"""
UserLabelDelTask: EnumMsgType.ValueType  # 1227
"""删除个人标签"""
UserLabelModifyTask: EnumMsgType.ValueType  # 1228
"""新增或修改个人标签"""
UserLabelSetTask: EnumMsgType.ValueType  # 1229
"""设置标签任务（基于标签）"""
AddCustomerByIdTask: EnumMsgType.ValueType  # 1230
"""通过微信好友的openid添加客户"""
GetContactInfoTask: EnumMsgType.ValueType  # 1231
"""获取联系人信息"""
AcceptCustomerTask: EnumMsgType.ValueType  # 1232
"""通过新客户验证"""
UserSetLabelTask: EnumMsgType.ValueType  # 1233
"""联系人(客户）设置标签（基于客户）开发中"""
SetUserMemoTask: EnumMsgType.ValueType  # 1234
"""修改备注 开发中"""
PhoneStateTask: EnumMsgType.ValueType  # 1235
"""获取手机状态"""
MsgRevokeTask: EnumMsgType.ValueType  # 1236
"""消息撤回"""
SearchMsgTask: EnumMsgType.ValueType  # 1237
"""消息搜索"""
AddCustomerByGroupTask: EnumMsgType.ValueType  # 1238
"""外部群加客户"""
ForwardMsgTask: EnumMsgType.ValueType  # 1239
"""转发消息"""
ForwardMultiTask: EnumMsgType.ValueType  # 1240
"""多条转发"""
GetGroupMemberTask: EnumMsgType.ValueType  # 1241
"""获取群聊成员信息"""
AddEmojiTask: EnumMsgType.ValueType  # 1242
"""添加自定义表情"""
VoiceTransTextTask: EnumMsgType.ValueType  # 1243
"""语音消息转文字"""
JoinGroupInviteTask: EnumMsgType.ValueType  # 1244
"""加入群邀请"""
DelCustomerTask: EnumMsgType.ValueType  # 1245
"""删除客户"""
SendFriendVerifyTask: EnumMsgType.ValueType  # 1246
"""发送好友验证"""
GetConversationInfoTask: EnumMsgType.ValueType  # 1250
"""请求具体群聊的详细信息"""
GetExtUserIdTask: EnumMsgType.ValueType  # 1251
"""获取外部userId"""
GetExtUserIdTaskResult: EnumMsgType.ValueType  # 1252
"""获取外部userId返回结果"""
RunFunCardTask: EnumMsgType.ValueType  # 1253
"""执行App功能卡片（当前只支持 群发助手的群发通知）"""
DaKaTask: EnumMsgType.ValueType  # 1255
"""打卡任务"""
global___EnumMsgType = EnumMsgType

class _EnumErrorCode:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EnumErrorCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EnumErrorCode.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Success: _EnumErrorCode.ValueType  # 0
    """无错误"""
    NoRight: _EnumErrorCode.ValueType  # 1001
    """无权限"""
    InvalidParam: _EnumErrorCode.ValueType  # 1002
    """数据信息不合法"""
    InternalError: _EnumErrorCode.ValueType  # 1003
    """内部处理错误"""
    TargetNotOnline: _EnumErrorCode.ValueType  # 1004
    """发送消息或指令时对方不在线"""
    InfoNotExists: _EnumErrorCode.ValueType  # 1005

class EnumErrorCode(_EnumErrorCode, metaclass=_EnumErrorCodeEnumTypeWrapper):
    """全局错误码表"""

Success: EnumErrorCode.ValueType  # 0
"""无错误"""
NoRight: EnumErrorCode.ValueType  # 1001
"""无权限"""
InvalidParam: EnumErrorCode.ValueType  # 1002
"""数据信息不合法"""
InternalError: EnumErrorCode.ValueType  # 1003
"""内部处理错误"""
TargetNotOnline: EnumErrorCode.ValueType  # 1004
"""发送消息或指令时对方不在线"""
InfoNotExists: EnumErrorCode.ValueType  # 1005
global___EnumErrorCode = EnumErrorCode

class _EnumGender:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EnumGenderEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EnumGender.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownGender: _EnumGender.ValueType  # 0
    """未知"""
    Male: _EnumGender.ValueType  # 1
    """男"""
    Female: _EnumGender.ValueType  # 2
    """女"""

class EnumGender(_EnumGender, metaclass=_EnumGenderEnumTypeWrapper):
    """性别枚举"""

UnknownGender: EnumGender.ValueType  # 0
"""未知"""
Male: EnumGender.ValueType  # 1
"""男"""
Female: EnumGender.ValueType  # 2
"""女"""
global___EnumGender = EnumGender

class _EnumContentType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EnumContentTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EnumContentType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownContent: _EnumContentType.ValueType  # 0
    """未知内容"""
    Text: _EnumContentType.ValueType  # 1
    """文本内容"""
    Picture: _EnumContentType.ValueType  # 2
    """图片消息"""
    Voice: _EnumContentType.ValueType  # 3
    """语音消息"""
    Video: _EnumContentType.ValueType  # 4
    """视频消息"""
    System: _EnumContentType.ValueType  # 5
    """系统消息"""
    Link: _EnumContentType.ValueType  # 6
    """链接消息"""
    LinkExt: _EnumContentType.ValueType  # 7
    """扩展的链接消息（小程序分享等），内容为xml格式，暂未使用"""
    File: _EnumContentType.ValueType  # 8
    """文件发送"""
    NameCard: _EnumContentType.ValueType  # 9
    """名片"""
    Location: _EnumContentType.ValueType  # 10
    """位置信息"""
    LuckyMoney: _EnumContentType.ValueType  # 11
    """红包"""
    MoneyTrans: _EnumContentType.ValueType  # 12
    """转账"""
    WeApp: _EnumContentType.ValueType  # 13
    """小程序"""
    Emoji: _EnumContentType.ValueType  # 14
    """"""
    RoomManage: _EnumContentType.ValueType  # 15
    """群管理消息"""
    Sys_LuckyMoney: _EnumContentType.ValueType  # 16
    """领取红包消息"""
    RoomSystem: _EnumContentType.ValueType  # 17
    """群聊系统消息"""
    BizLink: _EnumContentType.ValueType  # 18
    """公众号文章"""
    AudioCall: _EnumContentType.ValueType  # 19
    """语音通话"""
    VideoCall: _EnumContentType.ValueType  # 20
    """视频通话"""
    NotifyMsg: _EnumContentType.ValueType  # 21
    """服务通知"""
    QuoteMsg: _EnumContentType.ValueType  # 22
    """引用通知"""
    ForwardMsg: _EnumContentType.ValueType  # 23
    """转发的消息记录"""
    SnsNotify: _EnumContentType.ValueType  # 24
    """朋友圈通知"""
    ShiPinHao: _EnumContentType.ValueType  # 25
    """视频号消息"""
    AppFunCard: _EnumContentType.ValueType  # 26
    """功能卡片"""
    UnSupport: _EnumContentType.ValueType  # 99
    """不支持的消息"""

class EnumContentType(_EnumContentType, metaclass=_EnumContentTypeEnumTypeWrapper):
    """聊天内容类型"""

UnknownContent: EnumContentType.ValueType  # 0
"""未知内容"""
Text: EnumContentType.ValueType  # 1
"""文本内容"""
Picture: EnumContentType.ValueType  # 2
"""图片消息"""
Voice: EnumContentType.ValueType  # 3
"""语音消息"""
Video: EnumContentType.ValueType  # 4
"""视频消息"""
System: EnumContentType.ValueType  # 5
"""系统消息"""
Link: EnumContentType.ValueType  # 6
"""链接消息"""
LinkExt: EnumContentType.ValueType  # 7
"""扩展的链接消息（小程序分享等），内容为xml格式，暂未使用"""
File: EnumContentType.ValueType  # 8
"""文件发送"""
NameCard: EnumContentType.ValueType  # 9
"""名片"""
Location: EnumContentType.ValueType  # 10
"""位置信息"""
LuckyMoney: EnumContentType.ValueType  # 11
"""红包"""
MoneyTrans: EnumContentType.ValueType  # 12
"""转账"""
WeApp: EnumContentType.ValueType  # 13
"""小程序"""
Emoji: EnumContentType.ValueType  # 14
""""""
RoomManage: EnumContentType.ValueType  # 15
"""群管理消息"""
Sys_LuckyMoney: EnumContentType.ValueType  # 16
"""领取红包消息"""
RoomSystem: EnumContentType.ValueType  # 17
"""群聊系统消息"""
BizLink: EnumContentType.ValueType  # 18
"""公众号文章"""
AudioCall: EnumContentType.ValueType  # 19
"""语音通话"""
VideoCall: EnumContentType.ValueType  # 20
"""视频通话"""
NotifyMsg: EnumContentType.ValueType  # 21
"""服务通知"""
QuoteMsg: EnumContentType.ValueType  # 22
"""引用通知"""
ForwardMsg: EnumContentType.ValueType  # 23
"""转发的消息记录"""
SnsNotify: EnumContentType.ValueType  # 24
"""朋友圈通知"""
ShiPinHao: EnumContentType.ValueType  # 25
"""视频号消息"""
AppFunCard: EnumContentType.ValueType  # 26
"""功能卡片"""
UnSupport: EnumContentType.ValueType  # 99
"""不支持的消息"""
global___EnumContentType = EnumContentType

class _EnumOnlineState:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EnumOnlineStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EnumOnlineState.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownState: _EnumOnlineState.ValueType  # 0
    """未知，在条件中可认为是全部"""
    Online: _EnumOnlineState.ValueType  # 1
    """在线"""
    Offline: _EnumOnlineState.ValueType  # 2
    """离线"""

class EnumOnlineState(_EnumOnlineState, metaclass=_EnumOnlineStateEnumTypeWrapper):
    """设备 ~ 微信号 在线状态枚举"""

UnknownState: EnumOnlineState.ValueType  # 0
"""未知，在条件中可认为是全部"""
Online: EnumOnlineState.ValueType  # 1
"""在线"""
Offline: EnumOnlineState.ValueType  # 2
"""离线"""
global___EnumOnlineState = EnumOnlineState

class _EnumAccountType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EnumAccountTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EnumAccountType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UnknownAccountType: _EnumAccountType.ValueType  # 0
    """未知"""
    Main: _EnumAccountType.ValueType  # 1
    """主账号"""
    SubUser: _EnumAccountType.ValueType  # 2
    """子账号"""

class EnumAccountType(_EnumAccountType, metaclass=_EnumAccountTypeEnumTypeWrapper):
    """账号类型"""

UnknownAccountType: EnumAccountType.ValueType  # 0
"""未知"""
Main: EnumAccountType.ValueType  # 1
"""主账号"""
SubUser: EnumAccountType.ValueType  # 2
"""子账号"""
global___EnumAccountType = EnumAccountType

class _EnumSendStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EnumSendStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EnumSendStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NoAction: _EnumSendStatus.ValueType  # 0
    """无状态"""
    Sending: _EnumSendStatus.ValueType  # 1
    """发送中"""
    SendSuccess: _EnumSendStatus.ValueType  # 17
    """发送成功"""
    SendError: _EnumSendStatus.ValueType  # 16
    """发送失败"""

class EnumSendStatus(_EnumSendStatus, metaclass=_EnumSendStatusEnumTypeWrapper):
    """消息发送状态"""

NoAction: EnumSendStatus.ValueType  # 0
"""无状态"""
Sending: EnumSendStatus.ValueType  # 1
"""发送中"""
SendSuccess: EnumSendStatus.ValueType  # 17
"""发送成功"""
SendError: EnumSendStatus.ValueType  # 16
"""发送失败"""
global___EnumSendStatus = EnumSendStatus

class _EnumForceOfflineReason:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EnumForceOfflineReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EnumForceOfflineReason.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NoReason: _EnumForceOfflineReason.ValueType  # 0
    """就是要下线你"""
    TickedByOther: _EnumForceOfflineReason.ValueType  # 1
    """别处登录挤下线了"""
    ByReAlloc: _EnumForceOfflineReason.ValueType  # 2
    """被重新分配"""
    ServiceExpired: _EnumForceOfflineReason.ValueType  # 3
    """服务到期"""

class EnumForceOfflineReason(_EnumForceOfflineReason, metaclass=_EnumForceOfflineReasonEnumTypeWrapper):
    """被强制下线的原因"""

NoReason: EnumForceOfflineReason.ValueType  # 0
"""就是要下线你"""
TickedByOther: EnumForceOfflineReason.ValueType  # 1
"""别处登录挤下线了"""
ByReAlloc: EnumForceOfflineReason.ValueType  # 2
"""被重新分配"""
ServiceExpired: EnumForceOfflineReason.ValueType  # 3
"""服务到期"""
global___EnumForceOfflineReason = EnumForceOfflineReason

@typing.final
class TransportMessage(google.protobuf.message.Message):
    """根传输消息"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    ACCESSTOKEN_FIELD_NUMBER: builtins.int
    MSGTYPE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    REFMESSAGEID_FIELD_NUMBER: builtins.int
    Id: builtins.int
    """消息Id(发送方内保持自增),请求中传入，响应中传回相同值"""
    AccessToken: builtins.str
    """设备通信token"""
    MsgType: global___EnumMsgType.ValueType
    """承载的具体消息类型"""
    RefMessageId: builtins.int
    """如果是针对某个消息的响应，这里写对应请求的id"""
    @property
    def Content(self) -> google.protobuf.any_pb2.Any:
        """具体的消息数据"""

    def __init__(
        self,
        *,
        Id: builtins.int = ...,
        AccessToken: builtins.str = ...,
        MsgType: global___EnumMsgType.ValueType = ...,
        Content: google.protobuf.any_pb2.Any | None = ...,
        RefMessageId: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Content", b"Content"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["AccessToken", b"AccessToken", "Content", b"Content", "Id", b"Id", "MsgType", b"MsgType", "RefMessageId", b"RefMessageId"]) -> None: ...

global___TransportMessage = TransportMessage
