"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TriggerHistoryMsgPushTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONVID_FIELD_NUMBER: builtins.int
    REFMSGID_FIELD_NUMBER: builtins.int
    LOCALID_FIELD_NUMBER: builtins.int
    FLAG_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    ConvId: builtins.int
    """会话RemoteId"""
    RefMsgId: builtins.int
    """起始消息remoteId"""
    LocalId: builtins.int
    """会话LocalId"""
    Flag: builtins.int
    """备用"""
    TaskId: builtins.int
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        ConvId: builtins.int = ...,
        RefMsgId: builtins.int = ...,
        LocalId: builtins.int = ...,
        Flag: builtins.int = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ConvId", b"ConvId", "Flag", b"Flag", "LocalId", b"LocalId", "RefMsgId", b"RefMsgId", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___TriggerHistoryMsgPushTaskMessage = TriggerHistoryMsgPushTaskMessage
