"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DeviceAppUpgradeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERNUMBER_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PACKAGENAME_FIELD_NUMBER: builtins.int
    PACKAGEURL_FIELD_NUMBER: builtins.int
    VerNumber: builtins.int
    """版本号"""
    Version: builtins.str
    """版本名称"""
    PackageName: builtins.str
    """包名称"""
    PackageUrl: builtins.str
    """软件包地址"""
    def __init__(
        self,
        *,
        VerNumber: builtins.int = ...,
        Version: builtins.str = ...,
        PackageName: builtins.str = ...,
        PackageUrl: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["PackageName", b"PackageName", "PackageUrl", b"PackageUrl", "VerNumber", b"VerNumber", "Version", b"Version"]) -> None: ...

global___DeviceAppUpgradeMessage = DeviceAppUpgradeMessage

@typing.final
class UpgradeDeviceAppNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    IMEI_FIELD_NUMBER: builtins.int
    APPINFOS_FIELD_NUMBER: builtins.int
    WxId: builtins.str
    IMEI: builtins.str
    @property
    def AppInfos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeviceAppUpgradeMessage]: ...
    def __init__(
        self,
        *,
        WxId: builtins.str = ...,
        IMEI: builtins.str = ...,
        AppInfos: collections.abc.Iterable[global___DeviceAppUpgradeMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AppInfos", b"AppInfos", "IMEI", b"IMEI", "WxId", b"WxId"]) -> None: ...

global___UpgradeDeviceAppNoticeMessage = UpgradeDeviceAppNoticeMessage
