"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserLabelSetTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    LABELID_FIELD_NUMBER: builtins.int
    ISCORP_FIELD_NUMBER: builtins.int
    ADDUSERS_FIELD_NUMBER: builtins.int
    DELUSERS_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """商家所属企业Wx号"""
    LabelId: builtins.int
    """标签id"""
    IsCorp: builtins.bool
    """是否为公司标签"""
    TaskId: builtins.int
    @property
    def AddUsers(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """新增的客户id"""

    @property
    def DelUsers(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """删除的客户id"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        LabelId: builtins.int = ...,
        IsCorp: builtins.bool = ...,
        AddUsers: collections.abc.Iterable[builtins.int] | None = ...,
        DelUsers: collections.abc.Iterable[builtins.int] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AddUsers", b"AddUsers", "DelUsers", b"DelUsers", "IsCorp", b"IsCorp", "LabelId", b"LabelId", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___UserLabelSetTaskMessage = UserLabelSetTaskMessage
