"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WUserLabelPushNotice_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserLabelModifyTaskResultNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    ERRMSG_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    Success: builtins.bool
    """是否成功"""
    ErrMsg: builtins.str
    """错误内容描述 获取 成功时附带的结果内容"""
    TaskId: builtins.int
    """任务id 在TaskResult中回传"""
    @property
    def Label(self) -> WUserLabelPushNotice_pb2.UserLabelMessage: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Success: builtins.bool = ...,
        ErrMsg: builtins.str = ...,
        TaskId: builtins.int = ...,
        Label: WUserLabelPushNotice_pb2.UserLabelMessage | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["Label", b"Label"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ErrMsg", b"ErrMsg", "Label", b"Label", "Success", b"Success", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___UserLabelModifyTaskResultNoticeMessage = UserLabelModifyTaskResultNoticeMessage
