"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserSetLabelTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    REMOTEID_FIELD_NUMBER: builtins.int
    LABELID_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """商家所属企业Wx号"""
    RemoteId: builtins.int
    """联系人id"""
    TaskId: builtins.int
    """repeated int64 CorpLabelId = 3; // 公司标签id
    repeated int64 PrivLabelId = 4; // 个人标签id
    """
    @property
    def LabelId(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        RemoteId: builtins.int = ...,
        LabelId: collections.abc.Iterable[builtins.int] | None = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["LabelId", b"LabelId", "RemoteId", b"RemoteId", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___UserSetLabelTaskMessage = UserSetLabelTaskMessage
