"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserLabelModifyTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    LABELNAME_FIELD_NUMBER: builtins.int
    LABELID_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """商家所属企业Wx号"""
    LabelName: builtins.str
    """标签名 id!=0 会修改标签名"""
    LabelId: builtins.int
    """标签id，0则新建标签（如存在同名标签则会失败）"""
    TaskId: builtins.int
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        LabelName: builtins.str = ...,
        LabelId: builtins.int = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["LabelId", b"LabelId", "LabelName", b"LabelName", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___UserLabelModifyTaskMessage = UserLabelModifyTaskMessage
