"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserLabelChangedNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Type: builtins.int
    """0 企业标签，1 个人标签"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Type: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Type", b"Type", "WxId", b"WxId"]) -> None: ...

global___UserLabelChangedNoticeMessage = UserLabelChangedNoticeMessage
