"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserLabelPushNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    LABELGROUPS_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    FINISHED_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """商家所属企业Wx号"""
    Page: builtins.int
    Finished: builtins.bool
    TaskId: builtins.int
    @property
    def LabelGroups(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UserLabelGroupMessage]:
        """用户标签组信息"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        LabelGroups: collections.abc.Iterable[global___UserLabelGroupMessage] | None = ...,
        Page: builtins.int = ...,
        Finished: builtins.bool = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Finished", b"Finished", "LabelGroups", b"LabelGroups", "Page", b"Page", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___UserLabelPushNoticeMessage = UserLabelPushNoticeMessage

@typing.final
class UserLabelMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    CREATETIME_FIELD_NUMBER: builtins.int
    GROUPID_FIELD_NUMBER: builtins.int
    Id: builtins.int
    """标签id"""
    Name: builtins.str
    """标签名称"""
    CreateTime: builtins.int
    """创建时间"""
    GroupId: builtins.int
    """标签组id"""
    def __init__(
        self,
        *,
        Id: builtins.int = ...,
        Name: builtins.str = ...,
        CreateTime: builtins.int = ...,
        GroupId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["CreateTime", b"CreateTime", "GroupId", b"GroupId", "Id", b"Id", "Name", b"Name"]) -> None: ...

global___UserLabelMessage = UserLabelMessage

@typing.final
class UserLabelGroupMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    CREATOR_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    Id: builtins.int
    """标签组id"""
    Creator: builtins.int
    """标签组创建者"""
    Name: builtins.str
    """标签组名称"""
    Type: builtins.int
    """类型：1 企业共享标签组，2 个人标签组"""
    @property
    def Labels(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UserLabelMessage]:
        """组内用户标签信息"""

    def __init__(
        self,
        *,
        Id: builtins.int = ...,
        Creator: builtins.int = ...,
        Name: builtins.str = ...,
        Type: builtins.int = ...,
        Labels: collections.abc.Iterable[global___UserLabelMessage] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Creator", b"Creator", "Id", b"Id", "Labels", b"Labels", "Name", b"Name", "Type", b"Type"]) -> None: ...

global___UserLabelGroupMessage = UserLabelGroupMessage
