"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class VoiceTransTextTaskMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONVID_FIELD_NUMBER: builtins.int
    MSGID_FIELD_NUMBER: builtins.int
    MSGREMOTEID_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """"""
    ConvId: builtins.int
    """会话RemoteId"""
    MsgId: builtins.int
    """消息Id"""
    MsgRemoteId: builtins.int
    """消息remoteid"""
    TaskId: builtins.int
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        ConvId: builtins.int = ...,
        MsgId: builtins.int = ...,
        MsgRemoteId: builtins.int = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ConvId", b"ConvId", "MsgId", b"MsgId", "MsgRemoteId", b"MsgRemoteId", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___VoiceTransTextTaskMessage = VoiceTransTextTaskMessage
