"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class VoiceTextNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    CONVID_FIELD_NUMBER: builtins.int
    MSGID_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    ConvId: builtins.int
    """会话RemoteId"""
    MsgId: builtins.int
    """服务端的主键id"""
    Content: builtins.str
    """消息唯一id"""
    State: builtins.int
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        ConvId: builtins.int = ...,
        MsgId: builtins.int = ...,
        Content: builtins.str = ...,
        State: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Content", b"Content", "ConvId", b"ConvId", "MsgId", b"MsgId", "State", b"State", "WxId", b"WxId"]) -> None: ...

global___VoiceTextNoticeMessage = VoiceTextNoticeMessage
