# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WVoiceTransTextTask.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WVoiceTransTextTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19WVoiceTransTextTask.proto\x12\x10Im.Scrm.Ww.Proto\"m\n\x19VoiceTransTextTaskMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x0e\n\x06\x43onvId\x18\x02 \x01(\x03\x12\r\n\x05MsgId\x18\x03 \x01(\x03\x12\x13\n\x0bMsgRemoteId\x18\x04 \x01(\x03\x12\x0e\n\x06TaskId\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WVoiceTransTextTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VOICETRANSTEXTTASKMESSAGE']._serialized_start=47
  _globals['_VOICETRANSTEXTTASKMESSAGE']._serialized_end=156
# @@protoc_insertion_point(module_scope)
