"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class WwOfflineNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    IMEI_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """微信内部全局唯一识别码"""
    IMEI: builtins.str
    """设备唯一号"""
    Type: builtins.int
    """登出原因，备用"""
    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        IMEI: builtins.str = ...,
        Type: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["IMEI", b"IMEI", "Type", b"Type", "WxId", b"WxId"]) -> None: ...

global___WwOfflineNoticeMessage = WwOfflineNoticeMessage
