"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import WTransport_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class WwOnlineNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    ALIAS_FIELD_NUMBER: builtins.int
    ACCTID_FIELD_NUMBER: builtins.int
    AVATAR_FIELD_NUMBER: builtins.int
    GENDER_FIELD_NUMBER: builtins.int
    JOB_FIELD_NUMBER: builtins.int
    PHONE_FIELD_NUMBER: builtins.int
    CORPID_FIELD_NUMBER: builtins.int
    ATTR_FIELD_NUMBER: builtins.int
    DEPARTIDS_FIELD_NUMBER: builtins.int
    IMEI_FIELD_NUMBER: builtins.int
    SYNCSTAT_FIELD_NUMBER: builtins.int
    CORPNAME_FIELD_NUMBER: builtins.int
    SHOWNAME_FIELD_NUMBER: builtins.int
    CORPSHORTNAME_FIELD_NUMBER: builtins.int
    UID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """账号ID"""
    Name: builtins.str
    """名称"""
    Alias: builtins.str
    """别称"""
    AcctId: builtins.str
    """内部账号"""
    Avatar: builtins.str
    """微信头像"""
    Gender: WTransport_pb2.EnumGender.ValueType
    """性别"""
    Job: builtins.str
    """职位"""
    Phone: builtins.str
    """"""
    CorpId: builtins.int
    """公司ID"""
    Attr: builtins.int
    """属性 备用"""
    IMEI: builtins.str
    """imei号"""
    SyncStat: builtins.int
    CorpName: builtins.str
    ShowName: builtins.str
    CorpShortName: builtins.str
    Uid: builtins.str
    @property
    def DepartIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """SimpleDepartMessage Departs = 11; // 部门信息"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Name: builtins.str = ...,
        Alias: builtins.str = ...,
        AcctId: builtins.str = ...,
        Avatar: builtins.str = ...,
        Gender: WTransport_pb2.EnumGender.ValueType = ...,
        Job: builtins.str = ...,
        Phone: builtins.str = ...,
        CorpId: builtins.int = ...,
        Attr: builtins.int = ...,
        DepartIds: collections.abc.Iterable[builtins.int] | None = ...,
        IMEI: builtins.str = ...,
        SyncStat: builtins.int = ...,
        CorpName: builtins.str = ...,
        ShowName: builtins.str = ...,
        CorpShortName: builtins.str = ...,
        Uid: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["AcctId", b"AcctId", "Alias", b"Alias", "Attr", b"Attr", "Avatar", b"Avatar", "CorpId", b"CorpId", "CorpName", b"CorpName", "CorpShortName", b"CorpShortName", "DepartIds", b"DepartIds", "Gender", b"Gender", "IMEI", b"IMEI", "Job", b"Job", "Name", b"Name", "Phone", b"Phone", "ShowName", b"ShowName", "SyncStat", b"SyncStat", "Uid", b"Uid", "WxId", b"WxId"]) -> None: ...

global___WwOnlineNoticeMessage = WwOnlineNoticeMessage
