# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WwOnlineNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WwOnlineNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WTransport_pb2 as WTransport__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14WwOnlineNotice.proto\x12\x10Im.Scrm.Ww.Proto\x1a\x10WTransport.proto\"\xc5\x02\n\x15WwOnlineNoticeMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\r\n\x05\x41lias\x18\x03 \x01(\t\x12\x0e\n\x06\x41\x63\x63tId\x18\x04 \x01(\t\x12\x0e\n\x06\x41vatar\x18\x05 \x01(\t\x12,\n\x06Gender\x18\x06 \x01(\x0e\x32\x1c.Im.Scrm.Ww.Proto.EnumGender\x12\x0b\n\x03Job\x18\x07 \x01(\t\x12\r\n\x05Phone\x18\x08 \x01(\t\x12\x0e\n\x06\x43orpId\x18\t \x01(\x03\x12\x0c\n\x04\x41ttr\x18\n \x01(\x03\x12\x11\n\tDepartIds\x18\x0b \x03(\x03\x12\x0c\n\x04IMEI\x18\x0c \x01(\t\x12\x10\n\x08SyncStat\x18\r \x01(\x05\x12\x10\n\x08\x43orpName\x18\x0e \x01(\t\x12\x10\n\x08ShowName\x18\x0f \x01(\t\x12\x15\n\rCorpShortName\x18\x10 \x01(\t\x12\x0b\n\x03Uid\x18\x14 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WwOnlineNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WWONLINENOTICEMESSAGE']._serialized_start=61
  _globals['_WWONLINENOTICEMESSAGE']._serialized_end=386
# @@protoc_insertion_point(module_scope)
