"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
命名空间约定"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class WxFriendPushNoticeMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WXID_FIELD_NUMBER: builtins.int
    FRIENDS_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    PAGE_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    WxId: builtins.int
    """设备企业WX号"""
    Size: builtins.int
    Count: builtins.int
    Page: builtins.int
    TaskId: builtins.int
    @property
    def Friends(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___WxFriendMessage]:
        """好友信息模型 多个"""

    def __init__(
        self,
        *,
        WxId: builtins.int = ...,
        Friends: collections.abc.Iterable[global___WxFriendMessage] | None = ...,
        Size: builtins.int = ...,
        Count: builtins.int = ...,
        Page: builtins.int = ...,
        TaskId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Count", b"Count", "Friends", b"Friends", "Page", b"Page", "Size", b"Size", "TaskId", b"TaskId", "WxId", b"WxId"]) -> None: ...

global___WxFriendPushNoticeMessage = WxFriendPushNoticeMessage

@typing.final
class WxFriendMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    AVATAR_FIELD_NUMBER: builtins.int
    OPENID_FIELD_NUMBER: builtins.int
    UNIONID_FIELD_NUMBER: builtins.int
    HASSENT_FIELD_NUMBER: builtins.int
    Name: builtins.str
    """昵称"""
    Avatar: builtins.str
    """头像"""
    OpenId: builtins.str
    """openId"""
    UnionId: builtins.str
    """unionId contactKey"""
    HasSent: builtins.bool
    """是否已发送过邀请"""
    def __init__(
        self,
        *,
        Name: builtins.str = ...,
        Avatar: builtins.str = ...,
        OpenId: builtins.str = ...,
        UnionId: builtins.str = ...,
        HasSent: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["Avatar", b"Avatar", "HasSent", b"HasSent", "Name", b"Name", "OpenId", b"OpenId", "UnionId", b"UnionId"]) -> None: ...

global___WxFriendMessage = WxFriendMessage
