# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WWxFriendPushNotice.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'WWxFriendPushNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import WTransport_pb2 as WTransport__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19WWxFriendPushNotice.proto\x12\x10Im.Scrm.Ww.Proto\x1a\x10WTransport.proto\"\x98\x01\n\x19WxFriendPushNoticeMessage\x12\x0c\n\x04WxId\x18\x01 \x01(\x03\x12\x32\n\x07\x46riends\x18\x02 \x03(\x0b\x32!.Im.Scrm.Ww.Proto.WxFriendMessage\x12\x0c\n\x04Size\x18\x03 \x01(\x05\x12\r\n\x05\x43ount\x18\x04 \x01(\x05\x12\x0c\n\x04Page\x18\x05 \x01(\x05\x12\x0e\n\x06TaskId\x18\x06 \x01(\x03\"a\n\x0fWxFriendMessage\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0e\n\x06\x41vatar\x18\x02 \x01(\t\x12\x0e\n\x06OpenId\x18\x03 \x01(\t\x12\x0f\n\x07UnionId\x18\x04 \x01(\t\x12\x0f\n\x07HasSent\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WWxFriendPushNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WXFRIENDPUSHNOTICEMESSAGE']._serialized_start=66
  _globals['_WXFRIENDPUSHNOTICEMESSAGE']._serialized_end=218
  _globals['_WXFRIENDMESSAGE']._serialized_start=220
  _globals['_WXFRIENDMESSAGE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
