# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AcceptFriendAddRequestTask.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'AcceptFriendAddRequestTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n AcceptFriendAddRequestTask.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"\xd4\x02\n!AcceptFriendAddRequestTaskMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x10\n\x08\x46riendId\x18\x03 \x01(\t\x12\x11\n\tAddWithWW\x18\x04 \x01(\x08\x12\x64\n\tOperation\x18\x05 \x01(\x0e\x32Q.Jubo.JuLiao.IM.Wx.Proto.AcceptFriendAddRequestTaskMessage.EnumFriendAddOperation\x12\x0e\n\x06Remark\x18\x06 \x01(\t\x12\x12\n\nFriendNick\x18\x07 \x01(\t\x12\x10\n\x08ReplyMsg\x18\x08 \x01(\t\x12\x0e\n\x06TaskId\x18\t \x01(\x03\x12\x0e\n\x06OnlyWW\x18\n \x01(\x08\"<\n\x16\x45numFriendAddOperation\x12\n\n\x06Ignore\x10\x00\x12\n\n\x06\x41\x63\x63\x65pt\x10\x01\x12\n\n\x06Reject\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AcceptFriendAddRequestTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCEPTFRIENDADDREQUESTTASKMESSAGE']._serialized_start=62
  _globals['_ACCEPTFRIENDADDREQUESTTASKMESSAGE']._serialized_end=402
  _globals['_ACCEPTFRIENDADDREQUESTTASKMESSAGE_ENUMFRIENDADDOPERATION']._serialized_start=342
  _globals['_ACCEPTFRIENDADDREQUESTTASKMESSAGE_ENUMFRIENDADDOPERATION']._serialized_end=402
# @@protoc_insertion_point(module_scope)
