# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AddFriendNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'AddFriendNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransportMessage_pb2 as TransportMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x41\x64\x64\x46riendNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x16TransportMessage.proto\"\xfb\x01\n\x16\x41\x64\x64\x46riendNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x10\n\x08\x46riendId\x18\x02 \x01(\t\x12\x10\n\x08\x46riendNo\x18\x03 \x01(\t\x12\x12\n\nFriendNick\x18\x04 \x01(\t\x12\x0e\n\x06Reason\x18\x05 \x01(\t\x12\x0e\n\x06\x41vatar\x18\x06 \x01(\t\x12\x0e\n\x06Source\x18\x07 \x01(\x05\x12\x12\n\nSourceUser\x18\x08 \x01(\t\x12\x33\n\x06Gender\x18\t \x01(\x0e\x32#.Jubo.JuLiao.IM.Wx.Proto.EnumGender\x12\x10\n\x08Province\x18\n \x01(\t\x12\x0c\n\x04\x43ity\x18\x0b \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AddFriendNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDFRIENDNOTICEMESSAGE']._serialized_start=75
  _globals['_ADDFRIENDNOTICEMESSAGE']._serialized_end=326
# @@protoc_insertion_point(module_scope)
