# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AddFriendNameCardTask.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'AddFriendNameCardTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x41\x64\x64\x46riendNameCardTask.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"s\n\x1c\x41\x64\x64\x46riendNameCardTaskMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x10\n\x08MsgSvrId\x18\x03 \x01(\x03\x12\x0f\n\x07Message\x18\x04 \x01(\t\x12\x0e\n\x06Remark\x18\x05 \x01(\t\x12\x0e\n\x06TaskId\x18\x06 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AddFriendNameCardTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDFRIENDNAMECARDTASKMESSAGE']._serialized_start=56
  _globals['_ADDFRIENDNAMECARDTASKMESSAGE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
