# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BizContactPushNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'BizContactPushNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x42izContactPushNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"\x83\x01\n\x11\x42izContactMessage\x12\x10\n\x08Username\x18\x01 \x01(\t\x12\r\n\x05\x41lias\x18\x02 \x01(\t\x12\x10\n\x08Nickname\x18\x03 \x01(\t\x12\x0e\n\x06\x41vatar\x18\x04 \x01(\t\x12\x0c\n\x04Icon\x18\x05 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x06 \x01(\t\x12\x0f\n\x07\x43ompany\x18\x07 \x01(\t\"}\n\x1b\x42izContactPushNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12<\n\x08\x43ontacts\x18\x02 \x03(\x0b\x32*.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage\x12\x0e\n\x06TaskId\x18\x03 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BizContactPushNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIZCONTACTMESSAGE']._serialized_start=56
  _globals['_BIZCONTACTMESSAGE']._serialized_end=187
  _globals['_BIZCONTACTPUSHNOTICEMESSAGE']._serialized_start=189
  _globals['_BIZCONTACTPUSHNOTICEMESSAGE']._serialized_end=314
# @@protoc_insertion_point(module_scope)
