# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BizContactAddNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'BizContactAddNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BizContactPushNotice_pb2 as BizContactPushNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x42izContactAddNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x1a\x42izContactPushNotice.proto\"k\n\x1a\x42izContactAddNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12;\n\x07\x43ontact\x18\x02 \x01(\x0b\x32*.Jubo.JuLiao.IM.Wx.Proto.BizContactMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BizContactAddNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIZCONTACTADDNOTICEMESSAGE']._serialized_start=82
  _globals['_BIZCONTACTADDNOTICEMESSAGE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
