# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CDNDownloadFileTask.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'CDNDownloadFileTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x43\x44NDownloadFileTask.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"\xcb\x01\n\x1a\x43\x44NDownloadFileTaskMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x0e\n\x06\x43\x64nUrl\x18\x02 \x01(\t\x12\x0e\n\x06\x43\x64nKey\x18\x03 \x01(\t\x12\x36\n\x08\x46ileType\x18\x04 \x01(\x0e\x32$.Jubo.JuLiao.IM.Wx.Proto.CDNFileType\x12\x0e\n\x06\x46ileId\x18\x05 \x01(\t\x12\x0f\n\x07\x46ileFmt\x18\x06 \x01(\t\x12\x10\n\x08\x46ileSize\x18\x07 \x01(\x05\x12\x10\n\x08MsgSvrId\x18\x08 \x01(\x03*\xba\x01\n\x0b\x43\x44NFileType\x12\x13\n\x0fNoteMsg_Picture\x10\x00\x12\x11\n\rNoteMsg_Thumb\x10\x01\x12\x11\n\rNoteMsg_Video\x10\x02\x12\x10\n\x0cNoteMsg_File\x10\x03\x12\x13\n\x0f\x43hatMsg_Picture\x10\x04\x12\x11\n\rChatMsg_Thumb\x10\x05\x12\x11\n\rChatMsg_Video\x10\x06\x12\x10\n\x0c\x43hatMsg_File\x10\x07\x12\x11\n\rChatMsg_Emoji\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CDNDownloadFileTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CDNFILETYPE']._serialized_start=261
  _globals['_CDNFILETYPE']._serialized_end=447
  _globals['_CDNDOWNLOADFILETASKMESSAGE']._serialized_start=55
  _globals['_CDNDOWNLOADFILETASKMESSAGE']._serialized_end=258
# @@protoc_insertion_point(module_scope)
