# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChatRoomMembersNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ChatRoomMembersNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransportMessage_pb2 as TransportMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43hatRoomMembersNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x16TransportMessage.proto\"\xe5\x01\n\x0fStrangerMessage\x12\x0c\n\x04Wxid\x18\x01 \x01(\t\x12\r\n\x05\x41lias\x18\x02 \x01(\t\x12\x10\n\x08Nickname\x18\x03 \x01(\t\x12\x0e\n\x06\x41vatar\x18\x04 \x01(\t\x12\x0c\n\x04Type\x18\x05 \x01(\x05\x12\x33\n\x06Gender\x18\x06 \x01(\x0e\x32#.Jubo.JuLiao.IM.Wx.Proto.EnumGender\x12\x0f\n\x07\x43ountry\x18\x07 \x01(\t\x12\x10\n\x08Province\x18\x08 \x01(\t\x12\x0c\n\x04\x43ity\x18\t \x01(\t\x12\x0c\n\x04Memo\x18\n \x01(\t\x12\x11\n\tSignature\x18\x0b \x01(\t\"k\n\x1c\x43hatRoomMembersNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x39\n\x07Members\x18\x03 \x03(\x0b\x32(.Jubo.JuLiao.IM.Wx.Proto.StrangerMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChatRoomMembersNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STRANGERMESSAGE']._serialized_start=81
  _globals['_STRANGERMESSAGE']._serialized_end=310
  _globals['_CHATROOMMEMBERSNOTICEMESSAGE']._serialized_start=312
  _globals['_CHATROOMMEMBERSNOTICEMESSAGE']._serialized_end=419
# @@protoc_insertion_point(module_scope)
