# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChatRoomChangedNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ChatRoomChangedNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x43hatRoomChangedNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"\x8e\x01\n\x1c\x43hatRoomChangedNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x10\n\x08UserName\x18\x02 \x01(\t\x12\x39\n\x04What\x18\x03 \x01(\x0e\x32+.Jubo.JuLiao.IM.Wx.Proto.EnumChatRoomChange\x12\x0f\n\x07\x43ontent\x18\x04 \x01(\t*\xd6\x01\n\x12\x45numChatRoomChange\x12\x15\n\x11\x43hange_MemberList\x10\x00\x12\x17\n\x13\x43hange_PublicNotice\x10\x01\x12\x13\n\x0f\x43hange_NickName\x10\x02\x12\x13\n\x0f\x43hange_ShowName\x10\x03\x12\x15\n\x11\x43hange_MyShowName\x10\x04\x12\x10\n\x0c\x43hange_Owner\x10\x05\x12\x11\n\rChange_Avatar\x10\x06\x12\x14\n\x10\x43hange_MemberAdd\x10\x07\x12\x14\n\x10\x43hange_MemberDel\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChatRoomChangedNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENUMCHATROOMCHANGE']._serialized_start=202
  _globals['_ENUMCHATROOMCHANGE']._serialized_end=416
  _globals['_CHATROOMCHANGEDNOTICEMESSAGE']._serialized_start=57
  _globals['_CHATROOMCHANGEDNOTICEMESSAGE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
