# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CircleDetailNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'CircleDetailNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CircleNewPublishNotice_pb2 as CircleNewPublishNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x43ircleDetailNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x1c\x43ircleNewPublishNotice.proto\"p\n\x19\x43ircleDetailNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x41\n\x06\x43ircle\x18\x02 \x01(\x0b\x32\x31.Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CircleDetailNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CIRCLEDETAILNOTICEMESSAGE']._serialized_start=83
  _globals['_CIRCLEDETAILNOTICEMESSAGE']._serialized_end=195
# @@protoc_insertion_point(module_scope)
