# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CirclePushNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'CirclePushNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CircleNewPublishNotice_pb2 as CircleNewPublishNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43irclePushNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x1c\x43ircleNewPublishNotice.proto\"\xbc\x01\n\x17\x43irclePushNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x42\n\x07\x43ircles\x18\x02 \x03(\x0b\x32\x31.Jubo.JuLiao.IM.Wx.Proto.CircleInformationMessage\x12\x0c\n\x04Size\x18\x03 \x01(\x05\x12\r\n\x05\x43ount\x18\x04 \x01(\x05\x12\x0c\n\x04Page\x18\x05 \x01(\x05\x12\x0f\n\x07RetCode\x18\x06 \x01(\x05\x12\x0f\n\x07RetTips\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CirclePushNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CIRCLEPUSHNOTICEMESSAGE']._serialized_start=82
  _globals['_CIRCLEPUSHNOTICEMESSAGE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
