# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ConfigPushNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ConfigPushNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43onfigPushNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"K\n\x11\x42oolConfigMessage\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\x08\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x04 \x01(\t\"J\n\x10IntConfigMessage\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\x05\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x04 \x01(\t\"J\n\x10StrConfigMessage\x12\x0b\n\x03Key\x18\x01 \x01(\t\x12\r\n\x05Value\x18\x02 \x01(\t\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x65sc\x18\x04 \x01(\t\"\xf2\x01\n\x17\x43onfigPushNoticeMessage\x12\x0c\n\x04IMEI\x18\x01 \x01(\t\x12\x10\n\x08WeChatId\x18\x02 \x01(\t\x12=\n\tBoolConfs\x18\x07 \x03(\x0b\x32*.Jubo.JuLiao.IM.Wx.Proto.BoolConfigMessage\x12;\n\x08IntConfs\x18\x08 \x03(\x0b\x32).Jubo.JuLiao.IM.Wx.Proto.IntConfigMessage\x12;\n\x08StrConfs\x18\t \x03(\x0b\x32).Jubo.JuLiao.IM.Wx.Proto.StrConfigMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ConfigPushNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOLCONFIGMESSAGE']._serialized_start=51
  _globals['_BOOLCONFIGMESSAGE']._serialized_end=126
  _globals['_INTCONFIGMESSAGE']._serialized_start=128
  _globals['_INTCONFIGMESSAGE']._serialized_end=202
  _globals['_STRCONFIGMESSAGE']._serialized_start=204
  _globals['_STRCONFIGMESSAGE']._serialized_end=278
  _globals['_CONFIGPUSHNOTICEMESSAGE']._serialized_start=281
  _globals['_CONFIGPUSHNOTICEMESSAGE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
