# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ContactLabelInfoNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ContactLabelInfoNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x43ontactLabelInfoNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"J\n\x10LabelInfoMessage\x12\x0f\n\x07LabelId\x18\x01 \x01(\x05\x12\x11\n\tLabelName\x18\x02 \x01(\t\x12\x12\n\nCreateTime\x18\x03 \x01(\x03\"l\n\x1d\x43ontactLabelInfoNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x39\n\x06Labels\x18\x02 \x03(\x0b\x32).Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContactLabelInfoNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LABELINFOMESSAGE']._serialized_start=57
  _globals['_LABELINFOMESSAGE']._serialized_end=131
  _globals['_CONTACTLABELINFONOTICEMESSAGE']._serialized_start=133
  _globals['_CONTACTLABELINFONOTICEMESSAGE']._serialized_end=241
# @@protoc_insertion_point(module_scope)
