# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ContactLabelAddNotic.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ContactLabelAddNotic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ContactLabelInfoNotice_pb2 as ContactLabelInfoNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x43ontactLabelAddNotic.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x1c\x43ontactLabelInfoNotice.proto\"j\n\x1c\x43ontactLabelAddNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x38\n\x05Label\x18\x02 \x01(\x0b\x32).Jubo.JuLiao.IM.Wx.Proto.LabelInfoMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContactLabelAddNotic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTACTLABELADDNOTICEMESSAGE']._serialized_start=85
  _globals['_CONTACTLABELADDNOTICEMESSAGE']._serialized_end=191
# @@protoc_insertion_point(module_scope)
