# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ContactInfoNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ContactInfoNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ChatRoomMembersNotice_pb2 as ChatRoomMembersNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x43ontactInfoNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x1b\x43hatRoomMembersNotice.proto\"\x98\x01\n\x18\x43ontactInfoNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x39\n\x07\x43ontact\x18\x02 \x01(\x0b\x32(.Jubo.JuLiao.IM.Wx.Proto.StrangerMessage\x12\x0e\n\x06TaskId\x18\x03 \x01(\x03\x12\x0f\n\x07Success\x18\x04 \x01(\x08\x12\x0e\n\x06\x45rrMsg\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContactInfoNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTACTINFONOTICEMESSAGE']._serialized_start=82
  _globals['_CONTACTINFONOTICEMESSAGE']._serialized_end=234
# @@protoc_insertion_point(module_scope)
