# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ForwardMessageByContentTask.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ForwardMessageByContentTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ForwardMessageByContentTask.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"\x9c\x01\n\"ForwardMessageByContentTaskMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x11\n\tFriendIds\x18\x02 \x01(\t\x12\x10\n\x08MsgSvrId\x18\x03 \x01(\x03\x12\x0f\n\x07MsgType\x18\x04 \x01(\x05\x12\x0f\n\x07\x43ontent\x18\x05 \x01(\t\x12\x0e\n\x06TaskId\x18\x06 \x01(\x03\x12\r\n\x05Thumb\x18\x07 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ForwardMessageByContentTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FORWARDMESSAGEBYCONTENTTASKMESSAGE']._serialized_start=63
  _globals['_FORWARDMESSAGEBYCONTENTTASKMESSAGE']._serialized_end=219
# @@protoc_insertion_point(module_scope)
