# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FriendChangeNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'FriendChangeNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FriendAddNotice_pb2 as FriendAddNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x46riendChangeNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x15\x46riendAddNotice.proto\"e\n\x19\x46riendChangeNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x36\n\x06\x46riend\x18\x03 \x01(\x0b\x32&.Jubo.JuLiao.IM.Wx.Proto.FriendMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FriendChangeNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRIENDCHANGENOTICEMESSAGE']._serialized_start=76
  _globals['_FRIENDCHANGENOTICEMESSAGE']._serialized_end=177
# @@protoc_insertion_point(module_scope)
