# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FriendDetectResultNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'FriendDetectResultNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x46riendDetectResultNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"\xff\x01\n\x1f\x46riendDetectResultNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x0e\n\x06TaskId\x18\x02 \x01(\x03\x12\x11\n\tStartTime\x18\x03 \x01(\x03\x12\x0f\n\x07\x45ndTime\x18\x04 \x01(\x03\x12\x12\n\nIsFinished\x18\x05 \x01(\x08\x12\r\n\x05\x43ount\x18\x06 \x01(\x05\x12\x11\n\tSkipCount\x18\x07 \x01(\x05\x12\x10\n\x08\x44\x65lCount\x18\x08 \x01(\x05\x12\x0f\n\x07Zombies\x18\t \x03(\t\x12\x13\n\x0b\x42lockedList\x18\n \x03(\t\x12\x12\n\nBannedList\x18\x0b \x03(\t\x12\x14\n\x0c\x43\x61nceledList\x18\x0c \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FriendDetectResultNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRIENDDETECTRESULTNOTICEMESSAGE']._serialized_start=60
  _globals['_FRIENDDETECTRESULTNOTICEMESSAGE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
