# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FriendAddReqListNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'FriendAddReqListNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransportMessage_pb2 as TransportMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x46riendAddReqListNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x16TransportMessage.proto\"\x95\x02\n\x10\x46riendReqMessage\x12\x10\n\x08\x46riendId\x18\x01 \x01(\t\x12\x10\n\x08\x46riendNo\x18\x02 \x01(\t\x12\x12\n\nFriendNick\x18\x03 \x01(\t\x12\x0e\n\x06\x41vatar\x18\x04 \x01(\t\x12\x0e\n\x06Reason\x18\x05 \x01(\t\x12\x33\n\x06Gender\x18\x06 \x01(\x0e\x32#.Jubo.JuLiao.IM.Wx.Proto.EnumGender\x12\x10\n\x08Province\x18\x07 \x01(\t\x12\x0c\n\x04\x43ity\x18\x08 \x01(\t\x12\x0e\n\x06Source\x18\t \x01(\x05\x12\x12\n\nSourceUser\x18\n \x01(\t\x12\x0f\n\x07ReqTime\x18\x0b \x01(\x03\x12\r\n\x05State\x18\x0c \x01(\x05\x12\x10\n\x08\x46irstReq\x18\r \x01(\x03\"n\n\x1d\x46riendAddReqListNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12;\n\x08Requests\x18\x02 \x03(\x0b\x32).Jubo.JuLiao.IM.Wx.Proto.FriendReqMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FriendAddReqListNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRIENDREQMESSAGE']._serialized_start=82
  _globals['_FRIENDREQMESSAGE']._serialized_end=359
  _globals['_FRIENDADDREQLISTNOTICEMESSAGE']._serialized_start=361
  _globals['_FRIENDADDREQLISTNOTICEMESSAGE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
