# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetA8KeyTask.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'GetA8KeyTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12GetA8KeyTask.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"\x86\x01\n\x13GetA8KeyTaskMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x0c\n\x04Type\x18\x02 \x01(\x05\x12\x0b\n\x03Url\x18\x03 \x01(\t\x12\x10\n\x08UserName\x18\x04 \x01(\t\x12\x10\n\x08MsgSvrId\x18\x05 \x01(\t\x12\x0e\n\x06Reason\x18\x06 \x01(\x05\x12\x0e\n\x06TaskId\x18\x07 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetA8KeyTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETA8KEYTASKMESSAGE']._serialized_start=48
  _globals['_GETA8KEYTASKMESSAGE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
