# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PostSNSNewsTask.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'PostSNSNewsTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15PostSNSNewsTask.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"\x93\x07\n\x16PostSNSNewsTaskMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x02 \x01(\t\x12U\n\nAttachment\x18\x03 \x01(\x0b\x32\x41.Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskMessage.AttachmentMessage\x12\x0f\n\x07\x43omment\x18\x04 \x01(\t\x12\x0e\n\x06TaskId\x18\x05 \x01(\x03\x12O\n\x07Visible\x18\x06 \x01(\x0b\x32>.Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskMessage.VisibleMessage\x12\x10\n\x08SendSlow\x18\x07 \x01(\x08\x12G\n\x03Poi\x18\x08 \x01(\x0b\x32:.Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskMessage.PoiMessage\x12\x12\n\nExtComment\x18\t \x03(\t\x1a\xe8\x01\n\x11\x41ttachmentMessage\x12^\n\x04Type\x18\x01 \x01(\x0e\x32P.Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskMessage.AttachmentMessage.EnumAttachType\x12\x0f\n\x07\x43ontent\x18\x02 \x03(\t\"b\n\x0e\x45numAttachType\x12\x08\n\x04Link\x10\x00\x12\x0b\n\x07Picture\x10\x02\x12\x0e\n\nShortVideo\x10\x03\x12\r\n\tLongVideo\x10\x04\x12\r\n\tShiPinHao\x10\x05\x12\x0b\n\x07\x45xtLink\x10\x06\x1a\xdd\x01\n\x0eVisibleMessage\x12\\\n\x04Type\x18\x01 \x01(\x0e\x32N.Jubo.JuLiao.IM.Wx.Proto.PostSNSNewsTaskMessage.VisibleMessage.EnumVisibleType\x12\x0e\n\x06Labels\x18\x02 \x01(\t\x12\x0f\n\x07\x46riends\x18\x03 \x01(\t\"L\n\x0f\x45numVisibleType\x12\n\n\x06Public\x10\x00\x12\x0b\n\x07Private\x10\x01\x12\x0e\n\nWhoVisible\x10\x02\x12\x10\n\x0cWhoInvisible\x10\x03\x1aS\n\nPoiMessage\x12\x0c\n\x04\x43ity\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0f\n\x07\x41\x64\x64ress\x18\x03 \x01(\t\x12\x0b\n\x03Lat\x18\x04 \x01(\x02\x12\x0b\n\x03Lng\x18\x05 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PostSNSNewsTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTSNSNEWSTASKMESSAGE']._serialized_start=51
  _globals['_POSTSNSNEWSTASKMESSAGE']._serialized_end=966
  _globals['_POSTSNSNEWSTASKMESSAGE_ATTACHMENTMESSAGE']._serialized_start=425
  _globals['_POSTSNSNEWSTASKMESSAGE_ATTACHMENTMESSAGE']._serialized_end=657
  _globals['_POSTSNSNEWSTASKMESSAGE_ATTACHMENTMESSAGE_ENUMATTACHTYPE']._serialized_start=559
  _globals['_POSTSNSNEWSTASKMESSAGE_ATTACHMENTMESSAGE_ENUMATTACHTYPE']._serialized_end=657
  _globals['_POSTSNSNEWSTASKMESSAGE_VISIBLEMESSAGE']._serialized_start=660
  _globals['_POSTSNSNEWSTASKMESSAGE_VISIBLEMESSAGE']._serialized_end=881
  _globals['_POSTSNSNEWSTASKMESSAGE_VISIBLEMESSAGE_ENUMVISIBLETYPE']._serialized_start=805
  _globals['_POSTSNSNEWSTASKMESSAGE_VISIBLEMESSAGE_ENUMVISIBLETYPE']._serialized_end=881
  _globals['_POSTSNSNEWSTASKMESSAGE_POIMESSAGE']._serialized_start=883
  _globals['_POSTSNSNEWSTASKMESSAGE_POIMESSAGE']._serialized_end=966
# @@protoc_insertion_point(module_scope)
