# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: QueryHbDetailTaskResultNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'QueryHbDetailTaskResultNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#QueryHbDetailTaskResultNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"A\n\x0fHbRecordMessage\x12\x10\n\x08UserName\x18\x01 \x01(\t\x12\x0e\n\x06\x41mount\x18\x02 \x01(\x05\x12\x0c\n\x04Time\x18\x03 \x01(\t\"\xd3\x02\n$QueryHbDetailTaskResultNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x0f\n\x07Success\x18\x02 \x01(\x08\x12\x0e\n\x06\x45rrMsg\x18\x03 \x01(\t\x12\r\n\x05HbUrl\x18\x04 \x01(\t\x12\x10\n\x08TotalNum\x18\x05 \x01(\x05\x12\x13\n\x0bTotalAmount\x18\x06 \x01(\x05\x12\x0e\n\x06RecNum\x18\x07 \x01(\x05\x12\x11\n\tRecAmount\x18\x08 \x01(\x05\x12\x39\n\x07Records\x18\t \x03(\x0b\x32(.Jubo.JuLiao.IM.Wx.Proto.HbRecordMessage\x12\x0e\n\x06Sender\x18\n \x01(\t\x12\x0f\n\x07Wishing\x18\x0b \x01(\t\x12\x0e\n\x06HbType\x18\x0c \x01(\x05\x12\x0e\n\x06HbKind\x18\r \x01(\x05\x12\x10\n\x08HbStatus\x18\x0e \x01(\x05\x12\x11\n\tRevStatus\x18\x0f \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'QueryHbDetailTaskResultNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HBRECORDMESSAGE']._serialized_start=64
  _globals['_HBRECORDMESSAGE']._serialized_end=129
  _globals['_QUERYHBDETAILTASKRESULTNOTICEMESSAGE']._serialized_start=132
  _globals['_QUERYHBDETAILTASKRESULTNOTICEMESSAGE']._serialized_end=471
# @@protoc_insertion_point(module_scope)
