# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: RequestTalkMsgTaskResultNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'RequestTalkMsgTaskResultNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransportMessage_pb2 as TransportMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$RequestTalkMsgTaskResultNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x16TransportMessage.proto\"\xe1\x01\n%RequestTalkMsgTaskResultNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x10\n\x08\x46riendId\x18\x02 \x01(\t\x12=\n\x0b\x43ontentType\x18\x03 \x01(\x0e\x32(.Jubo.JuLiao.IM.Wx.Proto.EnumContentType\x12\x0f\n\x07\x43ontent\x18\x04 \x01(\x0c\x12\x10\n\x08MsgSvrId\x18\x06 \x01(\x03\x12\x0e\n\x06IsSend\x18\x07 \x01(\x08\x12\x12\n\nCreateTime\x18\x08 \x01(\x03\x12\x0e\n\x06Status\x18\t \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RequestTalkMsgTaskResultNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUESTTALKMSGTASKRESULTNOTICEMESSAGE']._serialized_start=90
  _globals['_REQUESTTALKMSGTASKRESULTNOTICEMESSAGE']._serialized_end=315
# @@protoc_insertion_point(module_scope)
