# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SendSmsTask.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'SendSmsTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11SendSmsTask.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"e\n\x12SendSmsTaskMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x0c\n\x04Imei\x18\x02 \x01(\t\x12\x0e\n\x06Number\x18\x03 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x04 \x01(\t\x12\x0e\n\x06TaskId\x18\x05 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SendSmsTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDSMSTASKMESSAGE']._serialized_start=46
  _globals['_SENDSMSTASKMESSAGE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
