# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SetConfigTask.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'SetConfigTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ConfigPushNotice_pb2 as ConfigPushNotice__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13SetConfigTask.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x16\x43onfigPushNotice.proto\"\xef\x01\n\x14SetConfigTaskMessage\x12\x0c\n\x04IMEI\x18\x01 \x01(\t\x12\x10\n\x08WeChatId\x18\x02 \x01(\t\x12=\n\tBoolConfs\x18\x07 \x03(\x0b\x32*.Jubo.JuLiao.IM.Wx.Proto.BoolConfigMessage\x12;\n\x08IntConfs\x18\x08 \x03(\x0b\x32).Jubo.JuLiao.IM.Wx.Proto.IntConfigMessage\x12;\n\x08StrConfs\x18\t \x03(\x0b\x32).Jubo.JuLiao.IM.Wx.Proto.StrConfigMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SetConfigTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETCONFIGTASKMESSAGE']._serialized_start=73
  _globals['_SETCONFIGTASKMESSAGE']._serialized_end=312
# @@protoc_insertion_point(module_scope)
