# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WeChatGroupSendTask.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'WeChatGroupSendTask.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19WeChatGroupSendTask.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\"\xb0\x02\n\x1aWeChatGroupSendTaskMessage\x12\x0e\n\x06TaskId\x18\x01 \x01(\x03\x12\x11\n\tFriendIds\x18\x03 \x03(\t\x12`\n\x0b\x43ontentType\x18\x04 \x01(\x0e\x32K.Jubo.JuLiao.IM.Wx.Proto.WeChatGroupSendTaskMessage.EnumGroupMsgContentType\x12\x0f\n\x07\x43ontent\x18\x05 \x01(\t\x12\x10\n\x08WeChatId\x18\x06 \x01(\t\x12\x10\n\x08\x44uration\x18\x07 \x01(\x05\x12\x10\n\x08Original\x18\x08 \x01(\x08\"F\n\x17\x45numGroupMsgContentType\x12\x08\n\x04Text\x10\x00\x12\x0b\n\x07Picture\x10\x01\x12\t\n\x05Voice\x10\x02\x12\t\n\x05Video\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WeChatGroupSendTask_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WECHATGROUPSENDTASKMESSAGE']._serialized_start=55
  _globals['_WECHATGROUPSENDTASKMESSAGE']._serialized_end=359
  _globals['_WECHATGROUPSENDTASKMESSAGE_ENUMGROUPMSGCONTENTTYPE']._serialized_start=289
  _globals['_WECHATGROUPSENDTASKMESSAGE_ENUMGROUPMSGCONTENTTYPE']._serialized_end=359
# @@protoc_insertion_point(module_scope)
