# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WeChatLoginNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'WeChatLoginNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransportMessage_pb2 as TransportMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17WeChatLoginNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x16TransportMessage.proto\"\x8e\x02\n\x18WeChatLoginNoticeMessage\x12\x12\n\nSupplierId\x18\x01 \x01(\x03\x12\x0f\n\x07UnionId\x18\x02 \x01(\x03\x12=\n\x0b\x41\x63\x63ountType\x18\x03 \x01(\x0e\x32(.Jubo.JuLiao.IM.Wx.Proto.EnumAccountType\x12U\n\x07WeChats\x18\x04 \x03(\x0b\x32\x44.Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeMessage.WeChatLoginMessage\x1a\x37\n\x12WeChatLoginMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x0f\n\x07IsLogin\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WeChatLoginNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WECHATLOGINNOTICEMESSAGE']._serialized_start=77
  _globals['_WECHATLOGINNOTICEMESSAGE']._serialized_end=347
  _globals['_WECHATLOGINNOTICEMESSAGE_WECHATLOGINMESSAGE']._serialized_start=292
  _globals['_WECHATLOGINNOTICEMESSAGE_WECHATLOGINMESSAGE']._serialized_end=347
# @@protoc_insertion_point(module_scope)
