# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: WeChatTalkToFriendNotice.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'WeChatTalkToFriendNotice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransportMessage_pb2 as TransportMessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eWeChatTalkToFriendNotice.proto\x12\x17Jubo.JuLiao.IM.Wx.Proto\x1a\x16TransportMessage.proto\"\xd7\x01\n\x1fWeChatTalkToFriendNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x10\n\x08\x46riendId\x18\x03 \x01(\t\x12=\n\x0b\x43ontentType\x18\x05 \x01(\x0e\x32(.Jubo.JuLiao.IM.Wx.Proto.EnumContentType\x12\x0f\n\x07\x43ontent\x18\x06 \x01(\x0c\x12\r\n\x05MsgId\x18\x07 \x01(\x03\x12\x10\n\x08msgSvrId\x18\x08 \x01(\x03\x12\x12\n\nCreateTime\x18\t \x01(\x03\x12\x0b\n\x03\x45xt\x18\n \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WeChatTalkToFriendNotice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WECHATTALKTOFRIENDNOTICEMESSAGE']._serialized_start=84
  _globals['_WECHATTALKTOFRIENDNOTICEMESSAGE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
